### ISSUE TITLE
[BUG] WiFi和流量网络切换时产生较大流量消耗

### ISSUE THREAD

**Issue by railzy** [Kr328/ClashForAndroid#1013]
**描述出现的错误**
经过多次尝试后发现，打开ClashForAndroid的情况下，在WiFi和流量网络切换时，产生了较大的流量，瞬间流量达到约1.2m/s。关闭ClashForAndroid再尝试切换网络，未发现激增流量，瞬间流量约10k/s

该流量大小似乎与配置文件中`dns`条目下的`nameserver`以及`fallback`中的dns服务器条数成正相关
在原有配置文件下，网络切换瞬间流量达到1.2m/s
而通过应用内置覆盖功能给`nameserver`只设置`223.5.5.5`,`fallback`只设置`8.8.8.8`，再尝试切换网络，瞬间产生的流量约为150k/s
再给`nameserver`设置`223.5.5.5和119.29.29.29`,`fallback`设置`8.8.8.8和1.1.1.1`，再尝试切换网络，发现瞬间产生流量约为260k/s

猜测是每次切换网络都同时向每个dns服务器查询dns，从而消耗了较多的流量？

**如何复现该错误**
复现步骤:
1. 打开ClashForAndroid
2. 在`nameserver`和`fallback`中设置大量dns服务器
3. 切换网络
4. 瞬间产生较大流量

**预期行为**
WiFi和流量网络切换时的不产生明显流量

**屏幕截图**
无

**设备信息 (请完成以下信息):**
 - 机型: 三星s10+
 - 系统/ROM: OneUI3.1
 - Android 版本 11
 - ROM版本 G9750ZCU5fUC2

**应用信息**
 - 版本: 2.4.1.premium
 - 安装包文件名: app-premium-universal-release.apk
 - 应用来源: GitHub

**附加信息**
暂无其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
allow-lan: false
log-level: info
mode: Rule
ipv6: true
dns:
  enable: true
  listen: :53
  ipv6: true
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - +.music.163.com
    - "*.126.net"
  nameserver:
    - tls://dns.rubyfish.cn:853
    - https://dns.alidns.com/dns-query
    - 223.5.5.5
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
    - https://rubyfish.cn/dns-query
  fallback:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://dns.quad9.net/dns-query
    - https://8.8.8.8/dns-query
  fallback-filter:
    geoip: true
    ipcidr: ~
    domain:
      - +.google.com
      - +.youtube.com
```

**日志**
粘贴日志以帮助侦测错误
```
未得到相关日志
```
