### ISSUE TITLE
[BUG] Google FCM 不能走代理

### ISSUE THREAD

**Issue by alexlee728** [Kr328/ClashForAndroid#1016]
**描述出现的错误**
打开代理情况下，Google FCM不能走代理
    规则中mtalk.google.com已经强制走某个节点，
    拨号键盘输入：`*#*#426#*#*`，显示正在连接mtalk.google.com【可以通过打开关闭WiFi再次连接】
    日志看不到：mtalk.google.com等域名连接，服务端也看不到
    已经选择允许所有应用走代理

**如何复现该错误**
复现步骤:
1. 拨号键盘输入`*#*#426#*#*`【用来查看Google FCM连接状态】
2. 打开代理【规则中设置mtalk.google.com等相关域名走某个节点，同时选择允许所有应用代理】
3. 关闭或打开WiFi【切换网络后查看Google FCM会重新连接】
4. 查看LOG，没有相关LOG显示走代理

**预期行为**
Clash For Android 可以正常代理Google FCM，测试了一下Shadowsocks的Android版本是正常的

**屏幕截图**
![1561621486238_ pic](https://user-images.githubusercontent.com/3183748/118923528-40d25780-b96e-11eb-9880-8e4e028e1170.jpg)
![1571621486239_ pic](https://user-images.githubusercontent.com/3183748/118923538-4334b180-b96e-11eb-8409-315ae8034ef8.jpg)

**设备信息 (请完成以下信息):**
 - 机型: EMUI 11
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 10
 - ROM版本 11.0.0.135

**应用信息**
 - 版本: 2.4.1.foss
 - 安装包文件名: app-foss-arm64-v8a-release.apk
 - 应用来源: GitHub

**附加信息**
偶发性（概率低）WiFi情况下CFA看到LOG，能连接成功，手机网络100%不成功

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
port: 7890
allow-lan: false
bind-address: "*"
mode: rule
log-level: silent
ipv6: false
hosts:
  "*.clash.dev": 127.0.0.1
  alpha.clash.dev: ::1
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
    - 1.1.1.1
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/16
  use-hosts: true
  fake-ip-filter:
    - "*.lan"
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - swscan.apple.com
    - mesu.apple.com
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - +.music.163.com
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - +.y.qq.com
    - +.music.tc.qq.com
    - aqqmusic.tc.qq.com
    - +.stream.qqmusic.qq.com
    - "*.xiami.com"
    - +.music.migu.cn
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - +.xboxlive.com
    - localhost.ptlogin2.qq.com
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - stun.*.*.*.*
    - lens.l.google.com
    - stun.l.google.com
    - "*.n.n.srv.nintendo.net"
  nameserver:
    - 114.114.114.114
    - 1.1.1.1
    - 223.5.5.5
  fallback:
    - tls://dns.google:853
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 0.0.0.0/32
      - 127.0.0.0/8
      - 240.0.0.0/4
clash-for-android:
  append-system-dns: true
```

**日志**
粘贴日志以帮助侦测错误
```
没有代理成功，无日志显示。见截图
```
