### ISSUE TITLE
process-name规则无法匹配谷歌服务和框架[BUG] 

### ISSUE THREAD

**Issue by xyzlsx** [Kr328/ClashForAndroid#1069]
**描述出现的错误**
请简洁的描述你遇到的错误
process-name规则按包名无法匹配谷歌服务和框架，match规则能匹配,谷歌商店和chrome等能用process-name匹配

**如何复现该错误**
复现步骤:
1. 分应用代理选谷歌服务，框架，商店，和chrome
2. 开启代理(rule)，日志，打开谷歌商店
3. 打开谷歌服务
4. 查看日志，谷歌商店命中process-name规则，谷歌服务只能用match规则

**预期行为**
清晰简单的描述你预期的应用应该表现的行为
process-name规则应该命中谷歌服务，框架
**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误
![Screenshot_2021-06-13-16-37-42-57](https://user-images.githubusercontent.com/77908852/121806601-1fba0980-cc83-11eb-80f3-430b079095ea.jpg)
![Screenshot_2021-06-13-16-35-06-31](https://user-images.githubusercontent.com/77908852/121806613-28124480-cc83-11eb-96f3-8a7ea869f3d6.jpg)
![IMG_20210613_164019](https://user-images.githubusercontent.com/77908852/121806618-2cd6f880-cc83-11eb-9323-f949beda8cd5.jpg)

**设备信息 (请完成以下信息):**
 - 机型: [例如: oppo a11]
 - 系统/ROM: [例如: coloros 11]
 - Android 版本 [例如: 11]
 - ROM版本 [例如: F.04]

**应用信息**
 - 版本: [例如: 2.3.22]
 - 安装包文件名: [例如: com.github.kr328.clash]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
port: 7900
socks-port: 7901
allow-lan: false
mode: Rule
log-level: info
external-controller: :9090
proxies: []
proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - DIRECT
      - Google
  - name: Google
    proxies: []
    type: select
rules:
  - PROCESS-NAME,com.android.chrome,Google
  - PROCESS-NAME,com.android.vending,Google
  - PROCESS-NAME,com.google.android.gm,Google
  - PROCESS-NAME,com.google.android.webview,Google
  - PROCESS-NAME,com.google.android.gms,Google
  - PROCESS-NAME,com.google.android.gsf,Google
  - PROCESS-NAME,com.mojang.minecraftpe,Google
  - MATCH,节点选择

```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```见截图
