### ISSUE TITLE
[BUG] Fire tv stick 4k 全局模式很多流媒体app报错

### ISSUE THREAD

**Issue by Lighsark** [Kr328/ClashForAndroid#1076]
**描述出现的错误**
Fire tv stick 4k 全局模式很多app无法代理。报错。
无法使用：Netflix, IMDB TV
正常使用：Hulu

**如何复现该错误**
复现步骤:
1. 全局模式，使用配置"Global"
2. 选择美国节点
3. 打开Netflix
4. Netflix报错

**预期行为**
App正常播放流媒体。

**屏幕截图**

**设备信息 (请完成以下信息):**
 - 机型: Fire stick 4k
 - 系统/ROM: 
 - Android 版本
 - ROM版本

**应用信息**
 - 版本: v2.4.9
 - 安装包文件名: app-premium-armeabi-v7a-release.apk
 - 应用来源: Github

**附加信息**
同一时间，使用完全相同的配置，相同的节点，在电脑上使用Clash for Windows，可正常访问使用Netflix(美区), IMDB TV。
故非节点问题。

**配置文件**
```yaml

port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090

dns:
  enable: true
  # listen: 0.0.0.0:53
  ipv6: false # 当此选项为 false 时, AAAA 请求将返回空

  # 以下填写的 DNS 服务器将会被用来解析 DNS 服务的域名
  # 仅填写 DNS 服务器的 IP 地址
  default-nameserver:
    - 223.5.5.5
    - 1.2.4.8
    #- 114.114.114.114
    #- 119.29.29.29
  enhanced-mode: redir-host # 或 fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP 地址池 (CIDR 形式)
  # use-hosts: true # 查询 hosts 并返回 IP 记录

  # 在以下列表的域名将不会被解析为 fake ip，这些域名相关的解析请求将会返回它们真实的 IP 地址
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com

  # 支持 UDP / TCP / DoT / DoH 协议的 DNS 服务，可以指明具体的连接端口号。
  # 所有 DNS 请求将会直接发送到服务器，不经过任何代理。
  # Clash 会使用最先获得的解析记录回复 DNS 请求
  nameserver:
    #如果你有自建的DNS服务器或专用网络的DNS服务器可在托管链接添加如 &dns=9.9.9.9 参数（9.9.9.9替换成你要自定义的DNS，注意，此DNS必须有效，否则将导致出错无法使用），自定义DNS将出现以下方
    
    #默认提供DoT / DoH 协议的DNS
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
    - tls://223.6.6.6
    #- https://dns.alidns.com/dns-query
    #- https://v6.rubyfish.cn/dns-query
    #- https://rubyfish.cn/dns-query
    #- https://223.6.6.6/dns-query
    #- https://doh.360.cn/dns-query
    #- tls://223.5.5.5
    #- tls://dns.alidns.com
    #- tls://13800000000.rubyfish.cn
    #- tls://dot.360.cn
    #- 223.5.5.5
    #- 119.29.29.29
    
  # 当 fallback 参数被配置时, DNS 请求将同时发送至上方 nameserver 列表和下方 fallback 列表中配置的所有 DNS 服务器.
  # 当解析得到的 IP 地址的地理位置不是 CN 时，clash 将会选用 fallback 中 DNS 服务器的解析结果。
  fallback:
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - tls://8.8.4.4
    #- https://cloudflare-dns.com/dns-query
    #- https://1.1.1.1/dns-query
    #- https://dns.twnic.tw/dns-query
    #- tls://1.0.0.1
    #- tls://dns.adguard.com:853

  # 如果使用 nameserver 列表中的服务器解析的 IP 地址在下方列表中的子网中，则它们被认为是无效的，
  # Clash 会选用 fallback 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 true 且 IP 地址的地理位置为 CN 时，
  # Clash 会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 false, 如果解析结果在 fallback-filter.ipcidr 范围内，
  # Clash 会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 采取以上逻辑进行域名解析是为了对抗 DNS 投毒攻击。
  fallback-filter:
    geoip: false
    ipcidr:
    # - 240.0.0.0/4
proxies:


proxy-groups:



rule-providers:
  Unbreak:
    type: http
    behavior: classical
    path: ./Rules/Unbreak.yaml
    url: https://cdn.jsdelivr.net/gh/tututo/Profiles@master/Clash/RuleSet/Unbreak.yaml
    interval: 86400
  Netflix等国外流媒体:
    type: http
    behavior: classical
    path: ./Rules/NetflixAndGlobalMedia.yaml
    url: https://cdn.jsdelivr.net/gh/tututo/Profiles@master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400
  Global:
    type: http
    behavior: classical
    path: ./Rules/Global.yaml
    url: https://cdn.jsdelivr.net/gh/tututo/Profiles@master/Clash/RuleSet/Global.yaml
    interval: 86400
  爱奇艺等国内流媒体:
    type: http
    behavior: classical
    path: ./Rules/iQiyiAndChinaMedia.yaml
    url: https://cdn.jsdelivr.net/gh/tututo/Profiles@master/Clash/RuleSet/StreamingMedia/StreamingCN.yaml
    interval: 86400
  China:
    type: http
    behavior: classical
    path: ./Rules/China.yaml
    url: https://cdn.jsdelivr.net/gh/tututo/Profiles@master/Clash/RuleSet/China.yaml
    interval: 86400
  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./Rules/ChinaIP.yaml
    url: https://cdn.jsdelivr.net/gh/tututo/Profiles@master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400  




rules:

  # 在 官网 - 资料编辑 - 你追加自定义Clash规则，优先级最高





  - RULE-SET,Unbreak,DIRECT
  - RULE-SET,Netflix等国外流媒体,🎬Netflix等国外流媒体
  - RULE-SET,爱奇艺等国内流媒体,📺爱奇艺等国内流媒体
  - RULE-SET,Global,🚧Proxy

  - RULE-SET,China,🇨🇳国内网站或资源
  - RULE-SET,ChinaIP,🇨🇳国内网站或资源

  # Local Area Network
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT

  # Tencent
  #- IP-CIDR,119.28.28.28/32,🇨🇳国内网站或资源
  #- IP-CIDR,182.254.116.0/24,🇨🇳国内网站或资源
  # GeoIP China
  #- GEOIP,CN,🇨🇳国内网站或资源
  # ip111.cn检测passgfw 的域名 ):就是这么个性...
  - DOMAIN-SUFFIX,sspanel.net,🚧Proxy
  # zhs
  - DOMAIN-SUFFIX,zhs.tw,🚧Proxy  
  - DOMAIN-SUFFIX,zhshi.gitlab.io,🚧Proxy

  - MATCH,🌵其它规则外
  # 致谢引用的各开源项目开发者 @DivineEngine @Hackl0us  
```

**日志**
```
<在此粘贴>
```
