### ISSUE TITLE
无法和adguard共存[BUG] 

### ISSUE THREAD

**Issue by eleven702** [Kr328/ClashForAndroid#1083]
**描述出现的错误**
1.ad应用管理关闭clash
2. ad开启socks5
3. clash关闭自动系统流量
4.手机无法连接网络

**设备信息 (请完成以下信息):**
 - 机型: 三星s10
 - 系统/ROM: oneui3.1
 - Android 版本 11
 - ROM版本 最新版

**应用信息**
 - 版本: 2.4.9
 - 安装包文件名: app-premium-arm64-v8a-release.apk
 - 应用来源: [例如: Google Play]

**附加信息**
手机无法联网

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml

port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```
