### ISSUE TITLE
[BUG] 无法和adguard共存

### ISSUE THREAD

**Issue by eleven702** [Kr328/ClashForAndroid#1084]
**描述出现的错误**
无法和adguard共存
ad关闭clash应用管理
ad开启socks5
clash关闭自动系统流量
开启ad和clash手机无法联网

 - 机型: 三星s10
 - 系统/ROM:oneui3.1
 - Android 版本11
 - ROM版本 5fue4

**应用信息**
 - 版本: 2.4.9
 - 安装包文件名:app-premium-arm64-v8a-release.apk
 - 应用来源: [例如: Google Play]

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
`
```
