### ISSUE TITLE
[BUG] 部分域名DNS出错

### ISSUE THREAD

**Issue by fxzxmicah** [Kr328/ClashForAndroid#1130]
**描述出现的错误**
***部分***网站会出现“域名未解析”错误 

**如何复现该错误**
复现步骤:
1. 略

**预期行为**
获取正确的域名解析

**屏幕截图**
![Screenshot_20210805_093229](https://user-images.githubusercontent.com/48860358/128277583-c07e2514-7090-41c5-b39e-49702664fd34.jpg)
![image](https://user-images.githubusercontent.com/48860358/128277620-99c9e113-a988-4a53-ba45-4f3f920f671d.png)

**设备信息 (请完成以下信息):**
 - 机型: vivo X21A
 - 系统/ROM: Funtouch 9.0
 - Android 版本 9
 - ROM版本 7.10.17

**应用信息**
 - 版本: 2.4.9
 - 安装包文件名: app-foss-arm64-v8a-release.apk
 - 应用来源: github

**附加信息**
在电脑上使用同一配置文件，使用Clash Core作为DNS服务器，未出现过此错误。

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
mixed-port: 1080
ipv6: true
allow-lan: true
mode: rule
log-level: info
external-controller: localhost:80
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 1.2.4.8
  enhanced-mode: redir-host
  use-hosts: true
  nameserver:
    - tls://dot.pub
    - tls://dns.alidns.com
  fallback:
    - https://doh.dns.sb/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.rubyfish.cn/dns-query
    - https://cloudflare-dns.com/dns-query
  fallback-filter:
    geoip: true
```

**日志**
粘贴日志以帮助侦测错误
```
无相关信息
```

***洋洋洒洒写了这么多，到最后一步记录Log了，一打开Log记录就自己全部恢复正常了？这个Bug够神奇。我把这个Issue先发出来吧，保不齐这只是暂时的***
