### ISSUE TITLE
[BUG]  My phone burnt down while using the app

### ISSUE THREAD

**Issue by Jasmine-Thorqua** [Kr328/ClashForAndroid#1137]
**Describe the bug**
When I have used this app for a while, my phone would became very hot and I have to quit the app. But this time I forgot. Then my phone burnt down.

**To Reproduce**
1. Simply launch the app
2. Keep it running in background

**Expected behavior**
I hope this app does not make the phone so hot

**Screenshots**
No

**Device Info (please complete the following information):**

 - Device: OPPO R11
 - ROM: Color OS
 - ROM Version: 5
 - Android Version: 8.1

**Application Info (please complete the following information):**

 - Version: 2.4.9
 - Apk File Name: app-premium-arm64-v8a-release.apk
 - Distribution Channel: GitHub

**Additional context**
no

**Configure**
Paste configure file which **removed server info** 
```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
secret: ''
dns:
  enable: true
  ipv6: false
  listen: '0.0.0.0:53'
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - +.msftconnecttest.com
    - +.msftncsi.com
    - +.xboxlive.com
    - msftconnecttest.com
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback-filter:
    geoip: true
```

**Logs**
Paste logs to help detect problem

```
no
```
