### ISSUE TITLE
[BUG] 长链接时间长之后不通

### ISSUE THREAD

**Issue by alexlee728** [Kr328/ClashForAndroid#1167]
**描述出现的错误**
长链接时间长了之后会出现不发送数据问题。例如：将FCM的域名走了代理后，明明显示是连接成功状态，但是搜不到推送，关闭代理重新打开，让FCM重新连接就立马收到推送。
看到一段Core修改，不知道和这个是否有关系：
![image](https://user-images.githubusercontent.com/3183748/131947313-6eb093fa-4ce8-4014-8437-592cd97c5ea0.png)

**如何复现该错误**
复现步骤:
1. Google FCM的域名和IP选择走代理或者DIRECT
2. 正常使用一段时间
3. 开始能收到FCM推送，之后就收不到，打开FCM页面（`*#*#426#*#*`）查看还是显示连接状态。但是其他非长连接软件使用正常
4. 重启Clash软件，FCM显示重新连接上，立马收到推送

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: Mate 40 Pro
 - 系统/ROM: Harmony OS 2
 - Android 版本 10
 - ROM版本 2.0.0.165

**应用信息**
 - 版本: 2.4.9.foss
 - 安装包文件名: app-foss-arm64-v8a-release.apk
 - 应用来源: GitHub

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: false
hosts:
  mtalk.google.com: 142.250.31.188
  alt1-mtalk.google.com: 64.233.171.188
  alt2-mtalk.google.com: 142.250.115.188
  alt3-mtalk.google.com: 173.194.77.188
  alt4-mtalk.google.com: 173.194.219.188
  alt5-mtalk.google.com: 142.250.112.188
  alt6-mtalk.google.com: 172.217.197.188
  alt7-mtalk.google.com: 108.177.12.188
  .dev: 127.0.0.1
dns:
  enable: true
  listen: 0.0.0.0:5353
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
    - 1.1.1.1
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.0/16
  use-hosts: true
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - time.*.com
    - time.*.*.com
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
    - 1.1.1.1
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
    - tls://dns.google:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 127.0.0.0/8
      - 0.0.0.0/8
      - 240.0.0.0/4
    domain:
      - +.github.com
      - +.twitter.com
      - +.facebook.com
      - +.youtube.com

  - name: 📢 谷歌FCM
    type: select
    proxies:
      - DIRECT
      - 🇺🇲 美国节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇯🇵 日本节点
      - 🇰🇷 韩国节点
      - 🇸🇬 狮城节点


- DOMAIN,alt1-mtalk.google.com,📢 谷歌FCM
 - DOMAIN,alt2-mtalk.google.com,📢 谷歌FCM
 - DOMAIN,alt3-mtalk.google.com,📢 谷歌FCM
 - DOMAIN,alt4-mtalk.google.com,📢 谷歌FCM
 - DOMAIN,alt5-mtalk.google.com,📢 谷歌FCM
 - DOMAIN,alt6-mtalk.google.com,📢 谷歌FCM
 - DOMAIN,alt7-mtalk.google.com,📢 谷歌FCM
 - DOMAIN,alt8-mtalk.google.com,📢 谷歌FCM
 - DOMAIN,mtalk.google.com,📢 谷歌FCM
 - IP-CIDR,64.233.177.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,64.233.186.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,64.233.187.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,64.233.188.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,64.233.189.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,74.125.23.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,74.125.24.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,74.125.28.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,74.125.127.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,74.125.137.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,74.125.203.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,74.125.204.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,74.125.206.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,108.177.125.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,142.250.4.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,142.250.10.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,142.250.31.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,142.250.96.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,172.217.194.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,172.217.218.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,172.217.219.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,172.253.63.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,172.253.122.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,173.194.175.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,173.194.218.188/32,📢 谷歌FCM,no-resolve
 - IP-CIDR,209.85.233.188/32,📢 谷歌FCM,no-resolve

```

**日志**
粘贴日志以帮助侦测错误
```
Patch selector 📢 谷歌FCM -> DIRECT
[TCP] 172.19.0.1:56078 --> 142.250.31.188:5228 match IPCIDR(142.250.31.188/32) using 📢 谷歌FCM[DIRECT]

```
