### ISSUE TITLE
[使用疑惑] 关于DNS的策略设置的疑问，以及其他使用疑惑。

### ISSUE THREAD

**Issue by Akariln** [Kr328/ClashForAndroid#1272]
开发者你好！打扰了，我有些疑问想集中请教一下，希望百忙之中能有时间给与解答。

**应用信息**

 - 版本: [2.4.14.premium]
 - 应用来源: [Google Play]

**问题如下**

1. **首先我想知道 CFA 内置预设的默认 DNS 设置是怎样的？**

   恳求能否使用 Clash 的配置语法表示出来？

   类似下面这样的：

```yaml
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: false
  fake-ip-filter:
    - '*.lan'
    - 'localhost.ptlogin2.qq.com'
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - https://doh.pub/dns-query
    - tls://1.1.1.1:853
  fallback-filter:
    geoip: false
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
  nameserver-policy:
```

2. **我想请问 CFA 的 DNS 策略设置应该怎么理解？**

   我能否这么理解？

> 不修改：不对配置文件做任何修改。
>
> 强制启用：强制启用配置文件里写好的DNS设置。
>
> 使用内置：使用软件内置预设(第一个问题)的DNS配置进行覆写，使用内置的策略。

​		我弄不懂的是，不修改和强制启用的区别，

​		特别是配置文件如果没写 DNS 的情况，这种情况下是不是使用的安卓系统的 DNS ？

3. **我想请问 CFA 支持 TUN 模式 吗？**

​		如果支持，我需要在配置文件里写下类似如下内容的配置吗？

​		还是说默认已经弄好了 (使用安卓的 API 之类的)，不需要用户去设置 TUN ？

```yaml
tun:
  enable: true
  stack: system
  dns-hijack:
    - 8.8.8.8:53
    - tcp://8.8.8.8:
  auto-route: true
  auto-detect-interface: true
```

4. **“为 VpnService 附加HTTP代理”** 选项开启后，是不是类似于 Surge iOS 的工作模式 (将自身注册为代理服务器，同时建立 TUN 虚拟网卡去接管不支持代理的程序)。还是说说这么理解是错误的，是其他的运行原理和逻辑，其作用和优势是什么，希望能解答一下小小疑惑。

**最后，非常感谢开发者们的辛勤贡献！**
