### ISSUE TITLE
[BUG] 无法访问 ipv6 only 的 rdp 主机

### ISSUE THREAD

**Issue by qwe7002** [Kr328/ClashForAndroid#1306]
**描述出现的错误**
无法访问 ipv6 only 的 rdp 主机

**如何复现该错误**
复现步骤:
1. 在clash中配置IP-CIDR6和DOMAIN设定
2. 使用微软官方Remote Desktop访问绑定了AAAA记录的域名
3. 提示无法链接

**预期行为**
清晰简单的描述你预期的应用应该表现的行为
能够正常连接rdp主机

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: 三星 fold3
 - Android 版本 11

**应用信息**
 - 版本: Google Store最新版本
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
mixed-port: 2000
allow-lan: false
mode: Rule
log-level: warning
ipv6: true

rules:
- DOMAIN-SUFFIX,reallmgmt.net,system3
- IP-CIDR6,2a0e:800:ff80::/48,system3
- MATCH,DIRECT

```

**日志**
粘贴日志以帮助侦测错误
```
日志中无法查看到访问域名的信息
```
