### ISSUE TITLE
[BUG] url_test自动测速对纯ipv6节点无效

### ISSUE THREAD

**Issue by jwstaceyOvO** [Kr328/ClashForAndroid#1314]
**描述出现的错误**
url_test自动测速对纯ipv6节点无效

**如何复现该错误**
复现步骤:
1. 配置文件已启用ipv6
2. 选中测速节点组的父节点组
3. 显示了所有ipv4节点的显示，所有纯ipv6节点延迟未显示
4. 当手动测速时所有节点正常显示延迟

**预期行为**
当选中测速节点组的父节点组时会进行对应节点组的自动测速，此时应同时显示所有节点包括纯ipv6节点的延迟

**屏幕截图**
![Inkedphoto_2021-12-21_23-39-51_LI](https://user-images.githubusercontent.com/38880537/146960889-c94ee95a-f622-4e39-8866-e991953bdc54.jpg)
![Inkedphoto_2021-12-21_23-42-25_LI](https://user-images.githubusercontent.com/38880537/146960896-f5f4861d-1535-4b8b-a85b-a71e4918e4fd.jpg)

**设备信息 (请完成以下信息):**
 - 机型: [例如: sony xperia 1 iii]
 - 系统/ROM: [Android 11]
 - Android 版本 [11]
 - ROM版本 [最新]

**应用信息**
 - 版本: [2.5.3/2.4.14]
 - 安装包文件名: [cfa-2.5.3-premium-arm64-v8a-release.apk/cfa-2.4.14-premium-arm64-v8a-release.apk)]
 - 应用来源: [例如: github]

**附加信息**
本错误可能在其他系统的clash客户端上也能复现，常见的vultr，aws已提供ipv6可用于测试

**配置文件**
```yaml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rule
ipv6: true
log-level: silent
external-controller: '0.0.0.0:9090'
secret: ''


**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```
