### ISSUE TITLE
[BUG] 访问谷歌中国IP被强制走代理

### ISSUE THREAD

**Issue by wpzzz** [Kr328/ClashForAndroid#1317]
**描述出现的错误**
使用google play安装app，被指向从中国源下载，例如r2---sn-ni57rn7y.googlevideo.com ，但是以此类域名被强制走代理，导致无法下载，反而关闭clash后能正常下载，同样配置在CFW中可以direct

**如何复现该错误**
复现步骤:
1. 载入我的配置
2. 浏览器访问r2---sn-ni57rn7y.googlevideo.com
3. 观察clash日志是direct还是走代理

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: cfa-2.5.3-premium-arm64-v8a-release.apk
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
dns:
  enable: true
  #listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip

  nameserver:
    - https://1.1.1.1/dns-query

节点信息

rules:
 - IP-CIDR,192.168.0.0/16,DIRECT
 - IP-CIDR,10.0.0.0/8,DIRECT
 - IP-CIDR,172.16.0.0/12,DIRECT
 - IP-CIDR,127.0.0.0/8,DIRECT
 - GEOIP,CN,DIRECT
 - MATCH,PROXY
```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```
