### ISSUE TITLE
[BUG] 无法添加snell节点

### ISSUE THREAD

**Issue by tefiszx** [Kr328/ClashForAndroid#1352]
**描述出现的错误**
在配置文件中添加snell节点后，保存提示**did not find expected key**

**如何复现该错误**
复现步骤:
在配置文件中的proxies段添加snell节点如下：
```
# Snell
  # Beware that there's currently no UDP support yet
  - name: "snell"
    type: snell
    server: server
    port: 12345
    psk: yourpsk
     version: 2
     obfs-opts:
       mode: http # or tls
       host: bing.com
```

**预期行为**
可以添加并使用snell节点

**应用信息**
 - 版本: [例如: 2.5.4 premium]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: github relase]
