### ISSUE TITLE
[BUG] 虎牙直播app无法播放视频（如果不能重现请直接关闭issue）

### ISSUE THREAD

**Issue by forever8938** [Kr328/ClashForAndroid#1358]
**描述出现的错误**
虎牙直播app无法播放视频

**如何复现该错误**
复现步骤:
1. 导入一个直连一切的配置，启动Clash
2. 打开虎牙直播app，播放任意一个视频
3. ...
4. ...

**预期行为**
立即播放视频

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: 所有版本
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: Github

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info


proxies:
  - name: "ss"
    type: ss
    server: 1.1.1.1
    port: 1234
    cipher: aes-128-gcm
    password: "."


rules:
  - MATCH,DIRECT


```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```
