### ISSUE TITLE
[BUG] TLS x509 cannot validate certificate, because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by niphor** [Kr328/ClashForAndroid#1362]
**描述出现的错误**
日志报错：`[TCP] dial Proxy (match Match/) to some.site:443 error: dial x.x.x.x:yyy error: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs`

其中： `x.x.x.x:yyy` 为`IP:端口`

证书用的是Let's Encrypt 的, 用`--keylength ec-256` 的签发的 ECC Wildcard证书。前2天刚renew，还有3个月过期

同样的配置在最新的ClashX Pro上没有遇到问题

去掉TLS验证降低安全性不太好，把IP加到证书里也不现实...

**如何复现该错误**
复现步骤:

1. 从2.5.3升级为2.5.4，相同配置文件，无法正常上网

2. 降级为2.5.3，相同的配置文件，可以使用

**设备信息 (请完成以下信息):**
 - 机型: MIX 4
 - 系统/ROM: MIUI 12.5
 - Android 版本: 11
 - ROM版本: 12.5.12.0(RKMCNXM)

**应用信息**
 - 版本: 2.5.4
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: Github

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
示例配置，完整配置我用的Hackl0us的`Clash_Premium.yaml`配置
```yaml
  - name: DEMO
    type: vmess
    server: x.x.x.x
    port: yyy
    uuid: uuid
    alterId: 123
    network: ws
    ws-path: /abc
    tls: true
    ws-headers:
      Host: demo.conf
```

**日志**
```
[TCP] dial Proxy (match Match/) to some.site:443 error: dial x.x.x.x:yyy error: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs
```
