### ISSUE TITLE
[BUG] 使用trojan grpc时，必须开关一次WIFI或流量或切换为Global模式才能使用，否则无法使用

### ISSUE THREAD

**Issue by xusenfa** [Kr328/ClashForAndroid#1372]
**描述出现的错误**
使用trojan grpc时，必须开关一次WIFI或流量或切换为Global模式才能使用，否则无法使用

**如何复现该错误**
复现步骤:
1. 启动clash
2. 出现bug
3. ...
4. ...

**预期行为**
正常上网

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]魅族16th，红米k30，小米10s，oppo reno 6 pro 等等，所有我测试的手机都100%复现
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [例如: 1.1.10]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: [例如: Google Play]

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
mixed-port: 7890
mode: Rule
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter: ["*.lan", stun.*.*.*, stun.*.*, time.windows.com, time.nist.gov, time.apple.com, time.asia.apple.com, "*.ntp.org.cn", "*.openwrt.pool.ntp.org", time1.cloud.tencent.com, time.ustc.edu.cn, pool.ntp.org, ntp.ubuntu.com, ntp.aliyun.com, ntp1.aliyun.com, ntp2.aliyun.com, ntp3.aliyun.com, ntp4.aliyun.com, ntp5.aliyun.com, ntp6.aliyun.com, ntp7.aliyun.com, time1.aliyun.com, time2.aliyun.com, time3.aliyun.com, time4.aliyun.com, time5.aliyun.com, time6.aliyun.com, time7.aliyun.com, "*.time.edu.cn", time1.apple.com, time2.apple.com, time3.apple.com, time4.apple.com, time5.apple.com, time6.apple.com, time7.apple.com, time1.google.com, time2.google.com, time3.google.com, time4.google.com, music.163.com, "*.music.163.com", "*.126.net", musicapi.taihe.com, music.taihe.com, songsearch.kugou.com, trackercdn.kugou.com, "*.kuwo.cn", api-jooxtt.sanook.com, api.joox.com, joox.com, y.qq.com, "*.y.qq.com", streamoc.music.tc.qq.com, mobileoc.music.tc.qq.com, isure.stream.qqmusic.qq.com, dl.stream.qqmusic.qq.com, aqqmusic.tc.qq.com, amobile.music.tc.qq.com, "*.xiami.com", "*.music.migu.cn", music.migu.cn, "*.msftconnecttest.com", "*.msftncsi.com", localhost.ptlogin2.qq.com, "*.*.*.srv.nintendo.net", "*.*.stun.playstation.net", xbox.*.*.microsoft.com, "*.ipv6.microsoft.com", "*.*.xboxlive.com", "speedtest.cros.wr.pvp.net"]
  default-nameserver: [119.29.29.29]
  nameserver: [119.29.29.29, https://223.5.5.5/dns-query]
#################################################################################################################################################################################################################################################################################
proxies:

  - {name: "1", server: *, port: 39950, type: trojan, password: "MoeSakura", network: grpc, sni: douyincdn.com, skip-cert-verify: true, udp: true, grpc-opts: {grpc-service-name: "MoeSakura"}}
  - {name: "2", server: *, port: 21180, type: trojan, password: "MoeSakura", network: grpc, sni: douyincdn.com, skip-cert-verify: true, udp: true, grpc-opts: {grpc-service-name: "MoeSakura"}}

proxy-groups:
  - name: 代理
    type: select
    proxies:
      - 1
      - 2
#################################################################################################################################################################################################################################################################################
rule-providers:
  greatfire:
    type: http
    behavior: domain
    url: "https://moesakura.oss-accelerate.aliyuncs.com/rule-providers/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://moesakura.oss-accelerate.aliyuncs.com/rule-providers/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
rules:
  - DOMAIN-SUFFIX,t.me,代理
  - DOMAIN-SUFFIX,tdesktop.com,代理
  - DOMAIN-SUFFIX,telegra.ph,代理
  - DOMAIN-SUFFIX,telegram.me,代理
  - DOMAIN-SUFFIX,telegram.org,代理
  - DOMAIN-SUFFIX,telesco.pe,代理
  - IP-CIDR,91.108.0.0/16,代理
  - IP-CIDR,109.239.140.0/24,代理
  - IP-CIDR,149.154.160.0/20,代理
  - DOMAIN-SUFFIX,googlevideo.com,代理
  - DOMAIN-SUFFIX,googleusercontent.com,代理
  - DOMAIN,www.googleapis.com,代理
  - DOMAIN,gdrive.xusenfa.workers.dev,代理
  - DOMAIN,gdworker.moesakura.cc,代理
  - DOMAIN-KEYWORD,steam,代理
  - DOMAIN,upos-hz-mirrorakam.akamaized.net,代理
  - DOMAIN-KEYWORD,cn-hk-eq-bcache,代理
  - RULE-SET,greatfire,代理
  - RULE-SET,cncidr,DIRECT
  - MATCH,代理

```

**日志**
粘贴日志以帮助侦测错误
```
<在此粘贴>
```
