### ISSUE TITLE
[BUG] Trojan+grpc problem on VPN mode

### ISSUE THREAD

**Issue by SSgumS** [Kr328/ClashForAndroid#1417]
### Describe the bug

Hello
When I use trojan+grpc server on VPN mode (`Route System Traffic`), nothing works. But if using vmess+tls+tcp everything works ok. The problem is just when using trojan+grpc in VPN mode.
And something else that's important, it becomes stable all of a sudden after about 5 minutes.

### To Reproduce

-

### Device Info

- Device: Redmi Note 9S
- ROM: MIUI Global 12.0.6 Stable
- Android Version: 10

### Application Info

- Version: 2.5.4-premium
- APK filename: -
- Distribution Channel: Google Play

### Configure File

```
mixed-port: 7890
allow-lan: false
bind-address: '*'
# authentication:
#   - "xyz:xyz"
mode: rule
log-level: debug
ipv6: true
external-controller: 127.0.0.1:9090

profile:
  store-selected: true

dns:
  enable: true
  ipv6: true
  default-nameserver:
    - 1.1.1.1
    - 208.67.222.222
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://doh.opendns.com/dns-query"

proxies:
  - name: "TrojanGrpc"
    type: trojan
    server: 100.100.100.100
    port: 443
    password: xyz
    udp: true
    skip-cert-verify: false
    network: grpc
    sni: xyz.xyz.xyz
    grpc-opts:
      grpc-service-name: xyz
  - name: "VmessTLSTCP"
    type: vmess
    server: 100.100.100.100
    port: 2083
    uuid: xyz
    alterId: 0
    cipher: none
    udp: true
    tls: true
    skip-cert-verify: true
    servername: xyz.xyz.xyz

proxy-groups:
  - name: Proxy
    type: select
    lazy: true
    proxies:
      - TrojanGrpc
      - VmessTLSTCP
      - Intercept
      - Direct
  - name: Intercept
    type: select
    lazy: true
    proxies:
      - REJECT
      - DIRECT
  - name: Direct
    type: select
    lazy: true
    proxies:
      - DIRECT
      - REJECT

rules:
  # Bypass Local
  - DOMAIN,localhost,Direct
  - DOMAIN-SUFFIX,local,Direct
  - IP-CIDR,127.0.0.0/8,Direct,no-resolve
  - IP-CIDR,172.16.0.0/12,Direct,no-resolve
  - IP-CIDR,192.168.0.0/16,Direct,no-resolve
  - IP-CIDR,10.0.0.0/8,Direct,no-resolve
  - IP-CIDR,100.64.0.0/10,Direct,no-resolve
  - IP-CIDR6,::1/128,Direct,no-resolve
  - IP-CIDR6,fc00::/7,Direct,no-resolve
  - IP-CIDR6,fe80::/10,Direct,no-resolve
  - IP-CIDR6,fd00::/8,Direct,no-resolve
  # Block Ads
  - DOMAIN-SUFFIX,ad.com,Intercept
  - MATCH,Proxy
```

### Logs

https://pastebin.com/qNz2q3ZD
