### ISSUE TITLE
[BUG] rule-providers 的规则匹配问题

### ISSUE THREAD

**Issue by returnL** [Kr328/ClashForAndroid#1452]
### 描述此错误

https://github.com/Dreamacro/clash/issues/2045
该问题在此处已有描述，我在 CFA 2.5.5 Premium 上验证也存在此问题，latest Core Premium 已解决此问题，请问能否同步更新一下CFA的Core版本

### 如何复现该错误

步骤 1: 导入config文件并配置rule.yaml
步骤 2: 开启CFA
步骤 3: 访问 zh.wikipedia.org

### 设备信息

- 机型: OnePlus 9 Pro
- 系统类型: ColorOS 12.1
- Android 版本: 12

### 应用信息

- 版本: 2.5.5-premium
- 安装包文件名: cfa-2.5.5-premium-arm64-v8a-release.apk
- 应用来源: GitHub

### 配置文件

config.yaml
```yaml
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxy-groups:
  - name: PROXY
    type: url-test
    use:
      - proxy
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: m
    type: select
    proxies:
      - DIRECT
      - PROXY
proxy-providers:
  proxy:
    type: http
    path: ./s.yml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
rules:
  - RULE-SET,rule,PROXY
  - MATCH,m
rule-providers:
  rule:
    type: file
    behavior: domain
    path: ./rule.yaml
    interval: 86400
```

rule.yaml
```yaml
payload:
  - '+.ja.wikipedia.org'
  - '+.wikipedia.org'
```

### 日志

[TCP] dial m (match Match/) to zh.wikipedia.org:443 error: dial tcp4 157.240.6.35:443: i/o timeout
