### ISSUE TITLE
[BUG] Help PTR failed: all DNS requests failed

### ISSUE THREAD

**Issue by ifoverload** [Kr328/ClashForAndroid#1463]
### Describe the bug

Why im getting this debug logcat:

```
[DNS Server] Exchange ;2.0.0.28.in-addr.arpa. IN  PTR failed: all DNS requests failed, first error: all DNS requests failed, first error: dial udp6 [fe80::7a85:f4ff:fe96:d693]:53: connect: invalid argument
```

As a result ipv6 just fail from test.
Is my configuration wrong? How to fix?

### To Reproduce

--

### Device Info

- Device: Xiaomi Redmi Poco X3
- ROM: MIUI Global 12 (Official)
- Android Version: 10 Oreo

### Application Info

- Version: 2.5.6-premium
- APK filename: cfa-2.5.6-premium-arm64-v8a-release.apk
- Distribution Channel: Github Releases

### Configure File

<details><summary>myconfig.yaml</summary><p>

```
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
mode: rule
log-level: debug
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
unified-delay: true
ipv6: true

profile:
  store-selected: true
  store-fake-ip: true

dns:
  enable: true
  ipv6: true
  use-host: true #lookup hosts and return IP record
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7894    
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853

  fallback:
    - tcp://1.1.1.1
    - tcp://8.8.8.8
    - 1.1.1.1
    - 8.8.8.8

  fallback-filter:
    geoip: true
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/16
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    
    
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "+.*"
  - "+.media.dssott.com"
  - "*.mcdn.bilivideo.cn"
  - ff.dorado.sdo.com
  - "*.ff14.sdo.com"
  - "*.ffxiv.com"
  - "*.finalfantasyxiv.com"
  - "*.square-enix.com"
  - "+.nflxvideo.net"
  - stun.l.google.com
  - lens.l.google.com
  - swdist.apple.com
  - swcdn.apple.com
  - swdownload.apple.com
  - swquery.apple.com
  - swscan.apple.com
  - mesu.apple.com
  - "*.router.asus.com"
  - "*.linksyssmartwifi.com"
  - "*.linksys.com"
  - heartbeat.belkin.com
  - "+.stun.*.*.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*"
  - stun.*.*.*
  - stun.*.*
  - proxy.golang.org
  - "+.wargaming.net"
  - "+.wowsgame.cn"
  - "+.wggames.cn"
  - "+.wotgame.cn"
  - "+.battlenet.com.cn"
  - xnotify.xboxlive.com
  - xbox.*.microsoft.com
  - "*.*.xboxlive.com"
  - xbox.*.*.microsoft.com
  - "+.stun.playstation.net"
  - "*.n.n.srv.nintendo.net"
  - "+.srv.nintendo.net"
  - localhost.sec.qq.com
  - localhost.ptlogin2.qq.com
  - msftncsi.com
  - msftconnecttest.com
  - "+.msftncsi.com"
  - "+.msftconnecttest.com"
  - music.migu.cn
  - "*.music.migu.cn"
  - "*.xiami.com"
  - amobile.music.tc.qq.com
  - aqqmusic.tc.qq.com
  - dl.stream.qqmusic.qq.com
  - isure.stream.qqmusic.qq.com
  - mobileoc.music.tc.qq.com
  - streamoc.music.tc.qq.com
  - "*.y.qq.com"
  - y.qq.com
  - joox.com
  - api.joox.com
  - api-jooxtt.sanook.com
  - "*.kuwo.cn"
  - trackercdn.kugou.com
  - songsearch.kugou.com
  - music.taihe.com
  - musicapi.taihe.com
  - "*.126.net"
  - "*.music.163.com"
  - music.163.com
  - time1.cloud.tencent.com
  - "+.pool.ntp.org"
  - "*.ntp.org.cn"
  - "*.time.edu.cn"
  - ntp7.*.com
  - ntp6.*.com
  - ntp5.*.com
  - ntp4.*.com
  - ntp3.*.com
  - ntp2.*.com
  - ntp1.*.com
  - ntp.*.com
  - time7.*.com
  - time6.*.com
  - time5.*.com
  - time4.*.com
  - time3.*.com
  - time2.*.com
  - time1.*.com
  - time.*.apple.com
  - time.*.edu.cn
  - time.*.gov
  - time.*.com
  - "*.home.arpa"
  - "*.local"
  - "*.test"
  - "*.localhost"
  - "*.invalid"
  - "*.example"
  - "*.localdomain"
  - "*.lan"
  - time.windows.com
  - time.nist.gov
  - time.apple.com
  - time.asia.apple.com
  - "*.ntp.org.cn"
  - "*.openwrt.pool.ntp.org"
  - time1.cloud.tencent.com
  - time.ustc.edu.cn
  - 0.id.pool.ntp.org
  - 1.id.pool.ntp.org
  - 2.id.pool.ntp.org
  - 3.id.pool.ntp.org
  
proxies:
  - {name: trojango1, server: ***, port: 443, udp: true, type: trojan, password: ***, sni: ***, skip-cert-verify: true, network: ws, ws-opts: {path: /trojan-go, headers: {Host: ***}}}
  - {name: trojango2, server: ***, port: 443, udp: true, type: trojan, password: ***, sni: ***, skip-cert-verify: true, network: ws, ws-opts: {path: /trojan-go, headers: {Host: ***}}}

proxy-groups:
  - name: lbtrojan
    type: load-balance
    strategy: consistent-hashing
    url: "http://www.gstatic.com/generate_204"
    interval: 200
    proxies:
      - trojango1
      - trojango2
      
rules:
 - MATCH, lbtrojan
```

</p></details>

### Logs

[DNS Server] Exchange ;2.0.0.28.in-addr.arpa. IN  PTR failed: all DNS requests failed, first error: all DNS requests failed, first error: dial udp6 [fe80::7a85:f4ff:fe96:d693]:53: connect: invalid argument

### Screenshot

<details><summary>ss version</summary><p>

![code](https://img001.prntscr.com/file/img001/Kh55JfFjRq2Jo_etXL4inw.jpg)

</p></details>

<details><summary>ss logcat</summary><p>

![code](https://img001.prntscr.com/file/img001/ns-zubQDSpizsodCJguv3w.jpg)

</p></details>

### Additional

--
