### ISSUE TITLE
[BUG] 测速后节点名字显示异常，出现�

### ISSUE THREAD

**Issue by returnL** [Kr328/ClashForAndroid#1479]
### 描述此错误

CFA在测速后会缩短显示的节点名，有时会导致节点名显示异常，变成�。
开发者选项中 最小宽度为 360 dp时
`📲 Telegram / SG / 🇸🇬 新加坡实验性 1` 这种情况下，测速后延迟均为三位数时，有时只显示国旗不显示后面的中文字，有时只显示�。具体请见下方截图。
`📲 Telegram / SG / 🇸🇬 新加坡高级 1` 这种情况下，节点名字少了一个中文，则无论怎么测速都不会显示�

如果将开发者选项中的最小宽度改大一些，改为441 dp。测速后不光显示国旗，还能显示几个中文字符，则无论SG选择哪个节点都不会出现�，具体请见下方截图。

似乎显示�和国旗emoji没有正常显示有关

### 如何复现该错误

步骤 1: 开发者选项中 最小宽度为 360 dp
步骤 2: 按下面所示的配置文件设置proxy-groups
步骤 3: SG选择name为 `🇸🇬 新加坡实验性 1` 的节点
步骤 4：在📲 Telegram 中选择SG，并进行测速

### 设备信息

- 机型: OnePlus 9 Pro
- 系统类型: ColorOS 12.1
- Android 版本: 12

### 应用信息

- 版本: 2.5.7-premium
- 安装包文件名: cfa-2.5.7-premium-arm64-v8a-release.apk
- 应用来源: GitHub Release

### 配置文件

```yml
proxy-groups:
- type: select
  name: 📲 Telegram
  proxies:
    - Proxy
    - HK
    - JP
    - US
    - SG
    - TW
- type: select
  name: SG
  proxies: ["🇸🇬 新加坡实验性 1","🇸🇬 新加坡高级 1","🇸🇬 新加坡高级 2","🇸🇬 新加坡高级 3","🇸🇬 新加坡标准 1","🇸🇬 新加坡标准 2","🇸🇬 新加坡标准 3","🇸🇬 新加坡标准 4","🇸🇬 新加坡标准 5","🇸🇬 新加坡标准 6","🇸🇬 新加坡标准 7","🇸🇬 新加坡标准 8"]
```

### 日志

```raw
无
```

### 屏幕截图

最小宽度360dp
![IMG_20220418_135258](https://user-images.githubusercontent.com/44701395/163761783-4fe3157a-4b7c-4b6a-8705-209c3223fb13.jpg)
![IMG_20220418_135320](https://user-images.githubusercontent.com/44701395/163761804-e913112f-c402-4770-ab98-3407e4e11c25.jpg)

最小宽度411dp
![Screenshot_2022-04-18-14-12-32-24_1ed813789000d97ac1c6fc69779c1198](https://user-images.githubusercontent.com/44701395/163763871-280a0f97-b741-459c-b5ee-410bc9501be0.jpg)

### 附加信息

开发者选项中 最小宽度为 360 dp
