### ISSUE TITLE
[BUG] 默认DNS策略是使用内置，但可能造成国外域名跳转到国家反诈中心页面

### ISSUE THREAD

**Issue by ckaak** [Kr328/ClashForAndroid#1498]
### 描述此错误

[TCP] dial 🎯 全球直连 (match GeoIP/CN) to xxxxxxxxx.com:443 error: dial tcp4 182.43.124.6:443: i/o timeout

国外的域名被解析到国家反诈中心页面，一些发卡网页就会这样。bit.ly这种国外短域名也会这样。策略修改成“不修改”就没问题。

### 如何复现该错误

软件默认DNS策略就是使用内置，但这样会造成部分国外网页跳国家反诈中心页面。

### 设备信息

- 机型:三星
- 系统类型:官方
- Android 版本:android12

### 应用信息

- 版本:2.5.8
- 安装包文件名:
- 应用来源:github

### 配置文件

```yml
这个问题出现在clash DNS策略默认使用内置
```

### 日志

```raw
[TCP] dial 🎯 全球直连 (match GeoIP/CN) to xxxxxxx.com:443 error: dial tcp4 182.43.124.6:443: i/o timeout
```

**Comment by Kr328** [comment]
自行修改规则 在命中 GEOIP 前 命中域名规则 即可避免

**Comment by ckaak** [comment]
> 自行修改规则 在命中 GEOIP 前 命中域名规则 即可避免

但我使用机场的配置，哪怕规则没有这个网页还是可以命中MATCH，而不是GEOIP，我怀疑是内置的dns被污染了，有一些国外网页也容易被重置。

**Comment by Kr328** [comment]
@ckaak 内置 DNS 本来就是被污染的 所以才需要域名规则来避免污染

**Comment by ckaak** [comment]
> @ckaak 内置 DNS 本来就是被污染的 所以才需要域名规则来避免污染

这个规则可能赶不上变化，我在windows使用规则里面没有bit.ly但可以命中MATCH，android就命中的geoip。
我不知道是不是使用了  fallback: 缘故，或者使用了加密dns。这个内置的  fallback:我没看到有配置，机场就有。

我不知道clash内置的dns加了  fallback:参数会不会好点。

**Comment by Kr328** [comment]
@ckaak 规则赶不上变化就引用别人维护的规则 内置 DNS 不好用自己写

内置的配置目标是尽可能适合更多的用例 

现有的 DNS 配置在命中域名规则后不需要进行额外的 DNS 查询 就能正确的无污染的连接到目标域名 这样的配置适合在绝大对数场景上会有更好的性能表现

至于 fallback 在域名规则完备的情况下 只会徒增查询流量而不存在任何意义

**Comment by nameless3721** [comment]
> > @ckaak 内置 DNS 本来就是被污染的 所以才需要域名规则来避免污染
> 
> 这个规则可能赶不上变化，我在windows使用规则里面没有bit.ly但可以命中MATCH，android就命中的geoip。 我不知道是不是使用了 fallback: - https://cloudflare-dns.com/dns-query 缘故，或者使用了加密dns。这个内置的 fallback:[]我没看到有配置，机场就有。
> 
> 我不知道clash内置的dns加了 fallback: - https://cloudflare-dns.com/dns-query 参数会不会好点。

并不会 因为解析成国内ip就不会用fallback了 最简单就是nameserver别用运营商dns和udp 53等会被劫持的dns 非常规端口也许可能避免 主要还是你手机或者网络可能会污染成国内ip这种fallback无法解决的
  nameserver:
    - tls://223.5.5.5
    - tls://223.6.6.6
    - tls://1.12.12.12
    - tls://120.53.53.53
    目前公共的暂时不会有污染成127和国内的情况 未来不清楚 虽然默认geoip用maxmind会有一些污染ip当国内的情况 这种得自己做域名规则或者不用maxmind的geoip了

**Comment by fireattack** [comment]
最近在 Android端遇到了好几次域名被污染到 `103.200.31.172` 的情况：

![image](https://user-images.githubusercontent.com/4130991/205798446-cdebb299-b955-4aa6-8fd3-89f1413ac4f4.png)

但是理论上以我都设置应该不可能发生（PC上也没发生过）

```
dns:
  enable: true
  listen: 127.0.0.1:8853
  default-nameserver:
    - 223.5.5.5
    - 1.0.0.1
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-filter:
  （略）
  nameserver:
    - https://223.6.6.6/dns-query
    - https://rubyfish.cn/dns-query
    - https://dns.pub/dns-query
  fallback:
    - https://dns.rubyfish.cn/dns-query
    - https://public.dns.iij.jp/dns-query
    - tls://8.8.4.4
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    ...
```

感觉是有些时候 Clash for Android 的 DNS 服务会莫名不起效
