### ISSUE TITLE
[BUG] 无法添加配置

### ISSUE THREAD

**Issue by re1oaded** [Kr328/ClashForAndroid#1506]
### 描述此错误

索尼电视从URL添加配置总是报错：
```
profile dose not contain `proxies` or `proxy-providers`
```
配置文件确认无问题，同样的链接和cfa，手机上和模拟器都能正常添加，实在不知道是什么原因导致的。

![er](https://user-images.githubusercontent.com/48444178/167398800-1746248c-b688-433e-a9be-db64d622f162.jpg)

### 如何复现该错误

添加配置

### 设备信息

索尼电视 SONY XR-75X90J 国行
Android 版本: 10

### 应用信息

- 版本: 2.5.8-premium
- 安装包文件名: [cfa-2.5.8-premium-universal-release.apk](https://github.com/Kr328/ClashForAndroid/releases/download/v2.5.8/cfa-2.5.8-premium-universal-release.apk)
- 应用来源: Github Releases

### 配置文件

```yml
mixed-port: 1080
allow-lan: false
mode: rule
log-level: warning

proxies:
  - {"name":"🇭🇰 Hong Kong 01","type":"ss","server":"ss.dev","port":26526,"cipher":"xchacha20-ietf-poly1305","password":"asdasd","udp":true,"plugin":"obfs","plugin-opts":{"mode":"http","host":"ds.download.windowsupdate.com"}}

proxy-groups:
- name: "PROXY"
  type: select
  proxies:
      - 🇭🇰 Hong Kong 01

rules:
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
```

### 日志

```raw
无
```
