### ISSUE TITLE
[BUG] 配置文件错误

### ISSUE THREAD

**Issue by cloud-jie** [Kr328/ClashForAndroid#1539]
### 描述此错误

师傅好，我想使用clashForAndroid抓包安卓手机app，但一直显示错误，我无法解决，网络上这块的资源也有限，所以过来叨扰一下师傅。
大概思路是设置clashForAndroid代理服务器端口为[Burp Suite](https://portswigger.net/burp)的监听端口（port：8080）
![image](https://user-images.githubusercontent.com/63632785/171043798-644052ab-33a7-4631-b891-321d555fa8c9.png)

### 如何复现该错误

这是我根据网上教程改的配置文件，见笑了，我使用clash for windwos编辑的文件，编辑保存未报错，但点击使用的时候报错了
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
  - name: v2p
    type: http
    serve: 127.0.0.1
    port: 8080
proxy-groups:
  - name: proxy
    type: select
    proxies: 
      - v2p
rules:
  - 'MATCH,proxy'
### 设备信息

我使用的是clash for windwos编写，因为在我映像中，是通用的

### 应用信息

- 版本:
- 安装包文件名:
- 应用来源:

### 配置文件

```yml
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
  - name: v2p
    type: http
    serve: 127.0.0.1
    port: 8080
proxy-groups:
  - name: proxy
    type: select
    proxies: 
      - v2p
rules:
  - 'MATCH,proxy'
```

### 日志

```raw
暂无
```
