### ISSUE TITLE
[BUG] Random name importing local provider using Premium version

### ISSUE THREAD

**Issue by djoeni** [Kr328/ClashForAndroid#1559]
### Describe the bug

When importing local provider using CFA Premium version it will generate random name which gonna resulted error when saving. There is different with FOSS version it will automatically filled with file name.

### To Reproduce

Step 1: Import proxy provider file from local storage
Step 2: Click ok with generated random file name without renaming it
Step 3: Saving configuration error
...

Error with warning that local provider not found.

### Device Info

- Device: Redmi 9T
- ROM: MIUI Global version 12
- Android Version: 11

### Application Info

- Version: 2.5.9-premium
- APK filename: cfa-2.5.9-premium-arm64-v8a-release.apk
- Distribution Channel: Github

### Configure File

```yml
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: info
allow-lan: true
bind-address: "*"

profile:
  store-selected: true
  #store-fake-ip: true

dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - tcp://1.0.0.1
  - tcp://8.8.8.8
  - 1.0.0.1
  - 8.8.8.8
  fallback:
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - tls://1.0.0.1:853
  - tls://8.8.8.8:853
  default-nameserver:
  - 1.0.0.1
  - 8.8.8.8

rules:
- MATCH,PROXY

proxy-groups:
- name: PROXY
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  use:
  - TROJAN

proxy-providers:
  TROJAN:
    type: http
    url: "url"
    interval: 3600
    path: ./trojan.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204
```

### Logs

```raw
No log because error when saving.
```

### Screenshot

![random_name](https://user-images.githubusercontent.com/20867437/174058299-e16b008c-f0f6-4624-981f-be6e318b939c.jpg)
![error_provider](https://user-images.githubusercontent.com/20867437/174058308-93093b70-b838-4f9b-84f8-a1762a05efa3.jpg)

### Additional

Hope that Premium version will not generated random name.
