### ISSUE TITLE
[BUG] 套cf的节点使用不了

### ISSUE THREAD

**Issue by fangxingweiai** [Kr328/ClashForAndroid#1626]
### 描述此错误

虽然cf的worker不行了，但是可以利用pages。heroku，套cf，host填写类似icook.tw域名，测延迟均失败且都不能使用，cfw，sagernet可以测其延迟和使用。

### 如何复现该错误

步骤 1: 白嫖一个heroku
步骤 2: 使用cf的pages来套cf
步骤 3: 服务器地址填icook.tw，zayo.com

### 设备信息

- 机型: 魅族闹特5
- 系统类型: flyme8
- Android 版本: 7

### 应用信息

- 版本: 2.5.11-premium
- 安装包文件名: cfa-2.5.11-premium-arm64-v8a-release.apk
- 应用来源: github

### 配置文件

```yml
port: 1087
socks-port: 1086
allow-lan: false
mode: Rule
log-level: silent
external-controller: 127.0.0.1:9090
proxies:

######################示例
- name: example
  type: vmess
  server: icook.tw
  port: 443
  uuid: fb290c46-f215-4c5f-a21f-78513c35dd43
  alterId: 0
  cipher: auto
  tls: true
  servername: test.pages.dev
  network: ws
  ws-opts:
    path: /test
    headers:
      Host: test.pages.dev

proxy-groups:
- name: proxy
  type: select
  proxies:
  - example
  
rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
rules:
- RULE-SET,reject,REJECT
- RULE-SET,proxy,proxy
- RULE-SET,direct,DIRECT
- GEOIP,CN,DIRECT
- MATCH,proxy
```

### 日志

```raw
无
```
