### ISSUE TITLE
[BUG] 2.4.14以后的版本，和adguard同时开启时不能正常代理工作

### ISSUE THREAD

**Issue by AndyandAndy00** [Kr328/ClashForAndroid#1650]
### 描述此错误

2.4.14版本的clash和adguard通过代理转发方式同时开启，代理功能正常，可以访问Google网站，经过测试，clash  2.4.14以后的更新的版本，与adguard共存时代理功能就不起作用。2.4.14该版本虽然可以正常与adguard共存使用，但是却不支持识别配置文件中proxy-providers下的filter参数，无法实现过滤。我希望clash和adguard共存使用的同时，也能对配置文件中的proxy-providers进行过滤。希望作者能提供解决方法

### 如何复现该错误

步骤 1: ...clash配置文件加入adguard dns参数
步骤 2: ...关闭clash自动路由系统流量
步骤 3: ...设置adguard代理转发至clash
...

### 设备信息

- 机型:Samsung s22 ultra
- 系统类型:ONE UI
- Android 版本:12

### 应用信息

- 版本:2.5.2-premium以及更新的版本
- 安装包文件名:cfa-2.5.2-premium-arm64-v8a-release.apk
- 应用来源:github 和 Googleplay

### 配置文件

```yml
port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: :9090
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:5450
  enhanced-mode: redir-host
  default-nameserver:
    - 119.29.29.29
    - 119.28.28.28
    - 1.0.0.1
    - 208.67.222.222
    - 1.2.4.8
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://1.1.1.1/dns-query
    - tls://dns.adguard.com:853

d: &d #订阅参数
  type: http
  interval: 3600
  path: ./Proxies/x.yaml
  url: 
  health-check:
   enable: true
   url: https://i.ytimg.com/generate_204
   interval: 300

proxy-providers:
  一:
    <<: *d
  hk1:
    <<: *d
    filter: ^(.*)(香港|HK|Hong)+(.*)$
  tw1:
    <<: *d
    filter: ^(.*)(台|TW|Tai)+(.*)$
  jp1:
    <<: *d
    filter: ^(.*)(日本|JP|韩|Japan)+(.*)$
  sg1:
    <<: *d
    filter: ^(.*)(新加坡|狮城|SG|Singapore)+(.*)$
  us1:
    <<: *d
    filter: ^(.*)(美国|US|States|American)+(.*)$
```

### 日志

```raw
无
```
