### ISSUE TITLE
[BUG] IPv6、fakeip模式，使用Google搜索Wedget 不停刷新请求

### ISSUE THREAD

**Issue by nguzlp** [Kr328/ClashForAndroid#1656]
### 描述此错误

使用IPv6（已从服务器端确认），fake-ip模式，用android系统自带的Google搜索wedget进行搜索，蓝色加载条加载一点点就会退回重新加载。可能是在不停发送请求，因为如果在这种状态多等待一会，就会被google提醒ip行为异常，要求reCAPTCHA验证。
**同**一台服务器用IPv4、fakeip模式下**不**存在该问题；
**不同**服务器用IPv6，fakeip模式**存在**同样的问题；
使用redir-host模式**不**存在该问题。

### 如何复现该错误

步骤 1: ...enable IPv6配置和dns；
步骤 2: ...服务器server: 字段直接使用IPv6地址，sni: 字段使用URL
步骤 3: ...选中服务器，开启代理，并使用Google搜索的Wedget进行搜索。
...

### 设备信息

- 机型: Sony Xperia 5 III
- 系统类型: Android 国际版
- Android 版本: 12

### 应用信息

- 版本:[v2.5.11]
- 安装包文件名:[cfa-2.5.11-premium-arm64-v8a-release.apk]
- 应用来源:(https://github.com/Kr328/ClashForAndroid/releases/tag/v2.5.11)

### 配置文件

```yml
port: 7890
socks-port: 7891

redir-port: 7892
allow-lan: false

mode: Rule

log-level: silent

external-controller: 127.0.0.1:9090

# 实验性功能
experimental:
  ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为true

hosts:
  'mtalk.google.com': 108.177.125.188
ipv6: true
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true # 当此选项为 false 时, AAAA 请求将返回空

  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
    - 8.8.8.8
    - "[2400:3200:baba::1]:53"
    - "[2001:4860:4860::8888]:53"

  enhanced-mode: fake-ip # 或 fake-ip  或者  redir-host
  fake-ip-range: 198.18.0.1/16 # Fake IP 地址池 (CIDR 形式)
  use-hosts: true # 查询 hosts 并返回 IP 记录
  fake-ip-filter:
    - "dns.msftncsi.com"
    - "www.msftncsi.com"
    - "www.msftconnecttest.com"
    - "+.msftconnecttest.com"

  nameserver:
    - 223.5.5.5
    - 114.114.114.114
    - 8.8.8.8
    - "[2400:3200:baba::1]:53"
    - "[2001:4860:4860::8888]:53"

  fallback:
    - 'https://1.1.1.1/dns-query'
    - 'tls://dns.google:853'
    - 'tls://dns.rubyfish.cn:853'
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 127.0.0.1/8
      - 0.0.0.0/32
--------------------
# Trojan - server
- name: "server"
  type: trojan
  server: IPv6:fa90::0010::63b7::
  port: 443
  password: A hidden password
  # udp: true
  sni: a.server.name # aka server name
  alpn:
     - h2
     - http/1.1
  # skip-cert-verify: true
```

### 日志

```raw
[TCP] 127.0.0.1:40716 --> www.google.com:443 match RuleSet(greatfire) using PROXY[server]
只有info级别的log，没有warning及以上的log。
```
