### ISSUE TITLE
[Feature Request] clash:// schema import base64

### ISSUE THREAD

**Issue by hiddify** [Kr328/ClashForAndroid#1675]
### Feature Description

using import from base64 is really useful.
Currently, shadowsocks, v2ray, outline use this method to import and expert their servers.

If we can have import from clipboard in clash for android it would be a great option. 

for example: `clash://install-config?base64=bWl4ZWQtcG9ydDogNzg5MAphbGxvdy1sYW46IGZhbHNlCmxvZy1sZXZlbDogaW5mbwpzZWNyZXQ6ICIiCmV4dGVybmFsLWNvbnRyb2xsZXI6IDEyNy4wLjAuMTo5MDkwCmlwdjY6IGZhbHNlCm1vZGU6IHJ1bGUKcHJveGllczoKICAtIG5hbWU6IFByb3h5CiAgICB0eXBlOiBodHRwCiAgICBzZXJ2ZXI6IHRlc3QKICAgIHBvcnQ6ICI0NDMiCiAgICB0bHM6IHRydWUKICAgIHNraXAtY2VydC12ZXJpZnk6IHRydWUKICAgIHNuaTogd3d3Lmdvb2dsZS5jb20KICAgIHVzZXJuYW1lOiB1c2VyCiAgICBwYXNzd29yZDogcGFzcwpydWxlczoKICAtIElQLUNJRFIsMTAuMTAuMzQuMC8yNCxQcm94eQogIC0gTUFUQ0gsRElSRUNUCg==`

In addition, it can support ss://, vmess://, ... protocol to have a complete and unified approach

**Comment by Kr328** [comment]
Clash for Android now support `clash://install-config?url=<encoded url>` scheme

Any benefit to use base64?

And we will not support any protocols other then clash configuration

**Comment by hiddify** [comment]
sorry for miss understanding. my idea is not to use URL, i mean using the whole config as base64. To remove the dependency for external https server which causes some issues in https://github.com/Kr328/ClashForAndroid/issues/1674

**Comment by Kr328** [comment]
Is is impossible.

A typical clash configuration require ~10K chars, encode it to base64 require ~15k, it is to long for URL

**Comment by hiddify** [comment]
You are right, but there are also small configurations like i have sent.

in this case clash can be an alternative client for shadowsocks and vmess by using only a protocol.

Please think more about it.

**Comment by Kr328** [comment]
@hiddify nope, don't assume the configuration file is small so that it won't cover most use cases.

**Comment by Kr328** [comment]
@hiddify And Clash require proxy & proxy group & rule to work, it must be provide by configuration that other client don't required.

**Comment by hiddify** [comment]
So, if it is so easy to solve:
if the protocol is `ss`, `vmess`,...
Create a simple proxy directive and add a proxy group type: select with only one element and rule with match all

For example, for shadowsocks with a plugin we have the following template and just replace the needed parts:

```
mixed-port: 7890
allow-lan: false
log-level: info
secret: ""
external-controller: 127.0.0.1:9090
ipv6: false
mode: rule
proxies:
  - name: Proxy1
    type: ss
    server: serverhost
    port: "443"
    cipher: chacha20-ietf-poly1305
    password: "password"
    plugin: obfs
    plugin-opts:
      mode: tls # or http
      host: www.bing.com
      
proxy-groups:
   - name: Proxy
     proxies:
       - Proxy1
     type: select
     
rules:
  - MATCH,DIRECT
```
