### ISSUE TITLE
[BUG] When updating Providers, the network does not go through the Proxy node in use

### ISSUE THREAD

**Issue by Kingsmanvn-Official** [Kr328/ClashForAndroid#1706]
### Describe the bug

When updating Proxy-providers, it will fail even if using the proxy node of one proxy-providers and then updating to another proxy-providers in the same configuration in use, it also fails.
Left I want the author to be able to let Proxy-providers and Rule-providers be updatable through the proxy the configuration is using in it.  Now when using that Providers container configuration and updating providers, the network goes directly without going through the proxy being run by the in-app configuration.

### To Reproduce

Step 1: Turn on clash vpn
Step 2: select Providers
Step 3: select update all Providers

### Device Info

- Device: Redmi Note 11 Pro Plus 5G
- ROM: MIUI Global 13.0.3
- Android Version: 12

### Application Info

- Version: 2.5.11-premium
- APK filename: cfa-2.5.11-premium-arm64-v8a-release.apk
- Distribution Channel: Github

### Configure File

```yml
port: 7890
socks-port: 7891
allow-lan: true
bind-address: '*'
mode: rule
ipv6: true
log-level: info
external-controller: '127.0.0.1:9090'
clash-for-android:
  append-system-dns: true
profile:
  store-selected: false
  store-fake-ip: true
experimental:
  ignore-resolve-fail: true
  sniff-tls-sni: false
dns:
  enable: true
  ipv6: true
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 45.90.28.1
    - 45.90.30.1
    - 119.29.29.29
  enhanced-mode: fake-ip
  use-hosts: true
  nameserver:
    - https://dns.google/dns-query
    - https://dns.adguard-dns.com/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.nextdns.io/fd88ba
    - https://cloudflare-dns.com/dns-query
  fallback:
    - https://dns.google/dns-query
    - https://dns.adguard-dns.com/dns-query
    - https://dns.quad9.net/dns-query
    - https://dns.nextdns.io/fd88ba
    - https://cloudflare-dns.com/dns-query
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 1.1.1.1:53
    - any:53
  auto-route: true
  auto-detect-interface: true
proxies:
  - name: 'ðŸ‡¸ðŸ‡¬ SG snell'
    type: snell
    server: xxx
    port: 443
    psk: xxx
    version: 3
    udp: true
    obfs-opts:
      mode: tls
      host: xxx
proxy-groups:
    - name: KINGSMANVN
      type: select
      use:
        - yuna
        - lienquan
      proxies:
        - "ðŸ‡¸ðŸ‡¬ SG snell"
proxy-providers:
  yuna:
    type: http
    url: "https://xxx"
    interval: 3600
    path: ./proxyset/yuna.yaml
    health-check:
      enable: true
      interval: 420
      url: http://www.gstatic.com/generate_204
  lienquan:
    type: http
    url: "https://xxx/lienquan"
    interval: 60060
    path: ./proxyset/lienquan.yaml
    health-check:
      enable: true
      interval: 840
      url: http://www.gstatic.com/generate_204
rule-providers:
  hostsvn:
    behavior: domain # domain, ipcidr or classical (premium core only)
    type: http
    url: "https://xxx/hostsVN-clash-rule.yaml"
    interval: 72240
    path: ./ruleset/hostsvn.yaml
  rejectfile:
    type: http
    behavior: domain
    url: "https://xxx/reject.txt"
    path: ./ruleset/rejectfile.yaml
    interval: 86400
rules:
  - RULE-SET,hostsvn,REJECT
  - RULE-SET,rejectfile,REJECT
  - MATCH,KINGSMANVN
```

### Logs

```raw
info: Start initial provider yuna
info: Start initial provider lienquan
info: Start initial compatible provider KINGSMANVN
info: Start initial rule provider hostsvn
info: Start initial rule provider rejectfile
info: HTTP proxy listening at: [::]:7890
info: SOCKS proxy listening at: [::]:7891
warning: Updating provider hostsvn: Get "https://xxx/hostsVN-clash-rule.yaml": net/http: TLS handshake timeout
warning: Updating provider yuna: Get "https://xxx": net/http: TLS handshake timeout
warning: Updating provider rejectfile: Get "https://xxx/reject.txt": net/http: TLS handshake timeout
warning: Updating provider lienquan: Get "https://xxx/lienquan": net/http: TLS handshake timeout
warning: Updating provider yuna: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `dm1lc3M...` into provider.ProxySchema
warning: Updating provider lienquan: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `dm1lc3M...` into provider.ProxySchema
```
