### ISSUE TITLE
google voice无法通话

### ISSUE THREAD

**Issue by poemsiu** [Kr328/ClashForAndroid#171]
使用google voice拨打美国电话无法接通，换全局模式也是一样，日志中udp的代理信息疯狂跳出[日志](https://cloud.189.cn/t/qq2UbqEjUrQn)
同节点路由器代理是能正常通话的 
```
# Logcat on 2020-02-28 14:04:34
1582869874207 INFO [TCP] 172.31.255.253:39340 --> extshort.weixin.qq.com using GLOBAL
1582869876253 INFO [TCP] 172.31.255.253:39344 --> extshort.weixin.qq.com using GLOBAL
1582869878561 INFO [TCP] 172.31.255.253:39348 --> extshort.weixin.qq.com using GLOBAL
1582869883067 INFO [UDP] 172.31.255.253:59649 --> lens.l.google.com using GLOBAL
1582869883072 INFO [TCP] 192.168.124.7:34221 --> 216.239.36.144 using GLOBAL
1582869883074 INFO [UDP] 172.31.255.253:55953 --> lens.l.google.com using GLOBAL
1582869883076 INFO [UDP] 172.31.255.253:50208 --> lens.l.google.com using GLOBAL
1582869883083 INFO [UDP] 172.31.255.253:43975 --> lens.l.google.com using GLOBAL
1582869883089 INFO [UDP] 172.31.255.253:53761 --> lens.l.google.com using GLOBAL
1582869883095 INFO [UDP] 172.31.255.253:54468 --> lens.l.google.com using GLOBAL
1582869883116 INFO [UDP] 172.31.255.253:52147 --> lens.l.google.com using GLOBAL
1582869883117 INFO [UDP] 172.31.255.253:60410 --> lens.l.google.com using GLOBAL
1582869883130 INFO [UDP] 172.31.255.253:48466 --> lens.l.google.com using GLOBAL
1582869883154 INFO [UDP] 172.31.255.253:43149 --> lens.l.google.com using GLOBAL
1582869884145 INFO [UDP] 172.31.255.253:36933 --> lens.l.google.com using GLOBAL
1582869884148 INFO [UDP] 172.31.255.253:40156 --> lens.l.google.com using GLOBAL
1582869884158 INFO [TCP] 172.31.255.253:55145 --> 216.239.36.144 using GLOBAL
1582869884161 INFO [UDP] 172.31.255.253:40842 --> lens.l.google.com using GLOBAL
1582869884163 INFO [UDP] 172.31.255.253:60190 --> lens.l.google.com using GLOBAL
1582869884178 INFO [UDP] 172.31.255.253:46463 --> lens.l.google.com using GLOBAL
1582869884196 INFO [UDP] 172.31.255.253:47707 --> lens.l.google.com using GLOBAL
1582869884196 INFO [UDP] 172.31.255.253:33396 --> lens.l.google.com using GLOBAL
1582869884207 INFO [UDP] 172.31.255.253:50369 --> lens.l.google.com using GLOBAL
1582869884243 INFO [UDP] 172.31.255.253:56920 --> lens.l.google.com using GLOBAL
1582869884246 INFO [UDP] 172.31.255.253:34941 --> lens.l.google.com using GLOBAL
1582869884781 INFO [TCP] 172.31.255.253:38052 --> 121.14.142.41 using GLOBAL
1582869884821 INFO [TCP] 172.31.255.253:35906 --> shmmsns.qpic.cn using GLOBAL
1582869884864 INFO [TCP] 172.31.255.253:35910 --> shmmsns.qpic.cn using GLOBAL
1582869885139 INFO [UDP] 192.168.124.7:55035 --> stun.l.google.com using GLOBAL
1582869885141 INFO [UDP] 172.31.255.253:40760 --> stun.l.google.com using GLOBAL
1582869885243 INFO [TCP] 172.31.255.253:38068 --> 121.14.142.41 using GLOBAL
1582869901886 INFO [TCP] 192.168.124.7:43931 --> 216.239.36.144 using GLOBAL
1582869901887 INFO [UDP] 172.31.255.253:49961 --> lens.l.google.com using GLOBAL
1582869901907 INFO [UDP] 172.31.255.253:43301 --> lens.l.google.com using GLOBAL
1582869901915 INFO [UDP] 172.31.255.253:38203 --> lens.l.google.com using GLOBAL
1582869901921 INFO [UDP] 172.31.255.253:57956 --> lens.l.google.com using GLOBAL
1582869901946 INFO [UDP] 172.31.255.253:41247 --> lens.l.google.com using GLOBAL
1582869901947 INFO [UDP] 172.31.255.253:50817 --> lens.l.google.com using GLOBAL
1582869901960 INFO [UDP] 172.31.255.253:32909 --> lens.l.google.com using GLOBAL
1582869901960 INFO [UDP] 172.31.255.253:53776 --> lens.l.google.com using GLOBAL
1582869901977 INFO [UDP] 172.31.255.253:37865 --> lens.l.google.com using GLOBAL
1582869901997 INFO [UDP] 172.31.255.253:59576 --> lens.l.google.com using GLOBAL
1582869906192 INFO [UDP] 172.31.255.253:38444 --> lens.l.google.com using GLOBAL
1582869906195 INFO [TCP] 192.168.124.7:38359 --> 216.239.36.144 using GLOBAL
1582869906205 INFO [UDP] 172.31.255.253:43855 --> lens.l.google.com using GLOBAL
1582869906212 INFO [UDP] 172.31.255.253:39951 --> lens.l.google.com using GLOBAL
1582869906234 INFO [UDP] 172.31.255.253:57216 --> lens.l.google.com using GLOBAL
1582869906236 INFO [UDP] 172.31.255.253:42148 --> lens.l.google.com using GLOBAL
1582869906237 INFO [UDP] 172.31.255.253:38534 --> lens.l.google.com using GLOBAL
1582869906262 INFO [UDP] 172.31.255.253:55896 --> lens.l.google.com using GLOBAL
1582869906270 INFO [UDP] 172.31.255.253:35534 --> lens.l.google.com using GLOBAL
1582869906282 INFO [UDP] 172.31.255.253:36146 --> lens.l.google.com using GLOBAL
1582869906291 INFO [UDP] 172.31.255.253:56847 --> lens.l.google.com using GLOBAL
1582869907129 INFO [TCP] 172.31.255.253:46565 --> 216.239.36.144 using GLOBAL
1582869907132 INFO [UDP] 172.31.255.253:42550 --> lens.l.google.com using GLOBAL
1582869907155 INFO [UDP] 172.31.255.253:34287 --> lens.l.google.com using GLOBAL
1582869907162 INFO [UDP] 172.31.255.253:59842 --> lens.l.google.com using GLOBAL
1582869907166 INFO [UDP] 172.31.255.253:48834 --> lens.l.google.com using GLOBAL
1582869907174 INFO [UDP] 172.31.255.253:50564 --> lens.l.google.com using GLOBAL
1582869907203 INFO [UDP] 172.31.255.253:34484 --> lens.l.google.com using GLOBAL
1582869907205 INFO [UDP] 172.31.255.253:50221 --> lens.l.google.com using GLOBAL
1582869907207 INFO [UDP] 172.31.255.253:51904 --> lens.l.google.com using GLOBAL
1582869907211 INFO [UDP] 172.31.255.253:56649 --> lens.l.google.com using GLOBAL
1582869907232 INFO [UDP] 172.31.255.253:42718 --> lens.l.google.com using GLOBAL
1582869908178 INFO [UDP] 172.31.255.253:36244 --> stun.l.google.com using GLOBAL
1582869908188 INFO [UDP] 192.168.124.7:38059 --> stun.l.google.com using GLOBAL
1582869924714 INFO [UDP] 172.31.255.253:37940 --> lens.l.google.com using GLOBAL
1582869924717 INFO [TCP] 192.168.124.7:56489 --> 216.239.36.144 using GLOBAL
1582869924721 INFO [UDP] 172.31.255.253:42603 --> lens.l.google.com using GLOBAL
1582869924736 INFO [UDP] 172.31.255.253:42542 --> lens.l.google.com using GLOBAL
1582869924748 INFO [UDP] 172.31.255.253:36803 --> lens.l.google.com using GLOBAL
1582869924755 INFO [UDP] 172.31.255.253:40269 --> lens.l.google.com using GLOBAL
1582869924773 INFO [UDP] 172.31.255.253:58968 --> lens.l.google.com using GLOBAL
1582869924780 INFO [UDP] 172.31.255.253:58236 --> lens.l.google.com using GLOBAL
1582869924789 INFO [UDP] 172.31.255.253:43652 --> lens.l.google.com using GLOBAL
1582869924803 INFO [UDP] 172.31.255.253:36631 --> lens.l.google.com using GLOBAL
1582869924817 INFO [UDP] 172.31.255.253:56593 --> lens.l.google.com using GLOBAL
```

**Comment by Kr328** [comment]
@poemsiu 不能直接拖动到 Github 文本框 直接上传吗

**Comment by poemsiu** [comment]
@Kr328 已经在文本框贴上了日志😂

**Comment by poemsiu** [comment]
目前又是能接不能打的状态

**Comment by Kr328** [comment]
This issue has no updated feedback and may have been fixed in latest release
此 Issue 没有后续且可能已经在最新版本中得到修复

**Comment by NewHanly** [comment]
大佬，这个问题并没有解决啊，我用的Play商店5月2日的版本，仍然不能用GV拨号，日志跟题主是一样的问题。

**Comment by NewHanly** [comment]
这是我的配置文件
```
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: info
external-controller: '127.0.0.1:9090'
secret: ''

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 117.50.10.10
    - 119.29.29.29
    - 114.114.114.114
    - 223.5.5.5
    - 223.6.6.6
  fallback:
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://dns.google:853

proxies:
  - name: ***
    type: trojan
    server: ***
    port: ***
    password: ***
    udp: true
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - DIRECT
      - REJECT
      - Ali

rules:
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
```
