### ISSUE TITLE
How can I use Tun mode on Android

### ISSUE THREAD

**Issue by kingsman1112** [Kr328/ClashForAndroid#1710]
### Feature Description

I use the configuration that declared Tun mode:
```
tun:
  enable: true
  stack: system
  dns-hijack:
    - 1.1.1.1:53
  auto-route: true
  auto-detect-interface: true
```
but when run it will still error `Start Tun interface error: permission denied`
Does Tun mode require the device to be Root to have the right to execute?
Can you tell me what to do to use Tun mode on Clash for Android?
Thank you!
