### ISSUE TITLE
[BUG] rule-set下规则的无效化

### ISSUE THREAD

**Issue by Yik0o** [Kr328/ClashForAndroid#1729]
### 描述此错误

将rule-set（reject集）放在第一位时，且当你长时间不走规则后，即不使用clash后并重新使用时，reject会覆盖提所有的规则（通过log看到的），不能进行正常的连接，只有重新更新reject集后，规则才能正常运行。
这是我使用的reject集 from https://github.com/Loyalsoldier/clash-rules
[https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt](url)

### 如何复现该错误

步骤 1: ...将rule-set（reject集）放置第一位
步骤 2: ...正常连接后熄屏，等待可能一两个小时后，亮屏使用手机发起网络连接。此时就会发现reject将会覆盖所有的规则，甚至是匹配所有的域名
步骤 3: ...此时只需更新外部资源下的reject集就能恢复正常
...

### 设备信息

- 机型: oppo find x2 pro
- 系统类型: color os 11
- Android 版本: 11

### 应用信息

- 版本: 2.5.9-premium
- 安装包文件名: cfa-2.5.9-premium-arm64-v8a-release.apk
- 应用来源: clash

### 配置文件

```yml
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: false
mode: rule
log-level: info
ipv6: false
hosts:
  services.googleapis.cn: 142.250.196.131
  www.google.cn: 142.250.196.131
external-controller: 0.0.0.0:9090
clash-for-android:
  append-system-dns: false
profile:
  tracing: true
dns:
  enable: false
  listen: 127.0.0.1:8853
  default-nameserver:
    - 223.5.5.5
    - 8.8.4.4
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - +.msftconnecttest.com
    - +.msftncsi.com
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - +.ipv6.microsoft.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.ff14.sdo.com"
    - ff.dorado.sdo.com
    - "*.mcdn.bilivideo.cn"
    - +.media.dssott.com
    - +.pvp.net
  nameserver:
    - 114.114.114.114
    - tls://223.5.5.5:853
    - tls://1.12.12.12
  fallback:
    - https://1.0.0.1/dns-query
    - https://public.dns.iij.jp/dns-query
    - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - +.facebook.com
      - +.twitter.com
      - +.google.com
      - +.googleapis.com
      - +.google.cn
      - +.googleapis.cn
      - +.xn--ngstr-lra8j.com
      - +.googlevideo.com
      - +.gvt1.com
      - +.gmail.com
      - +.youtube.com
      - +.youtu.be
      - +.gvt0.com
      - +.gvt2.com
      - +.gvt3.com
      - +.gstatic.com
      - +.265.com
      - +.2mdn.net
      - +.app-measurement.com
      - +.c.admob.com
      - +.clickserve.dartsearch.net
      - +.crl.pki.goog
      - +.doubleclick.net
      - +.firebase-settings.crashlytics.com
      - +.google-analytics.com
      - +.googleadservices.com
      - +.googleanalytics.com
      - +.googleoptimize.com
      - +.googlesyndication.com
      - +.googletagmanager.com
      - +.googletagservices.com
# 节点配置文件统一存放在 ./ 目录中
proxy-providers:
  # 从链接导入的配置文件
  foo: #香港
    type: http
    path: ./foo.yaml
    interval: 86400 
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 86400
  foo1: #台湾
    type: http
    path: ./foo1.yaml
    interval: 86400 
    health-check:
      enable: false
      interval: 86400
  foo2: #日本
    type: http
    path: ./foo2.yaml
    interval: 86400
    health-check:
      enable: false
      interval: 86400
  foo3: #新加坡
    type: http
    path: ./foo3.yaml
    url: "https://www.nameless13.com/sub?target=clash&url=https%3A%2F%2Fapi.flowercloud.xyz%2Fosubscribe.php%3Fsid%3D6301%26token%3DHkQ4J6gq1lN1%26sip002%3D1&expand=true&config=https%3A%2F%2Fraw.nameless13.com%2Fapi%2Fpublic%2Fdl%2FzKF9vFbb%2Feasy.ini&include=%E6%96%B0%E5%8A%A0%E5%9D%A1&emoji=true&list=false&udp=false&tfo=true&scv=false"
    interval: 86400 
    health-check:
      enable: false
      interval: 86400
  foo4: #美国
    type: http
    path: ./foo4.yaml
    interval: 86400
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 86400
  foo5: #其他
    type: http
    path: ./foo5.yaml
    interval: 86400
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 86400
# 从文件导入的配置文件
proxy-groups:
  - name: 🔰 节点选择
    type: select
    proxies:
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🚀 其他节点
      - DIRECT
  - name: 📲 电报吹水
    type: select
    proxies:
      - 🔰 节点选择
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🚀 其他节点
  - name: 📹 YouTube
    type: select
    proxies:
      - 🔰 节点选择
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🚀 其他节点
  - name: 🎥 NETFLIX
    type: select
    proxies:
      - 🔰 节点选择
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🚀 其他节点
  - name: 🎮️ Steam
  
    type: select
    interval: 86400 
    url: http://www.gstatic.com/generate_204
    proxies:
      - 🔰 节点选择
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🚀 其他节点
  - name: 🌍 国外媒体
    type: select
    proxies:
      - 🔰 节点选择
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🚀 其他节点
      - DIRECT
  - name: 🌏 BiliBili
    type: select
    proxies:
      - DIRECT
      - 🚀 其他节点
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
  - name: 🇭🇰 香港节点
    type: select
    interval: 86400 
    url: http://www.gstatic.com/generate_204
    use:
      - foo
  - name: 🇨🇳 台湾节点
    type: select
    interval: 86400 
    url: http://www.gstatic.com/generate_204
    use:
      - foo1
      
  - name: 🇸🇬 狮城节点
    type: select
    interval: 86400 
    url: http://www.gstatic.com/generate_204
    use:
      - foo3
      
  - name: 🇯🇵 日本节点
    type: select
    interval: 86400 
    url: http://www.gstatic.com/generate_204
    use:
      - foo2
      
  - name: 🇺🇲 美国节点
    type: select
    interval: 86400 
    url: http://www.gstatic.com/generate_204
    use:
      - foo4
      
  - name: 🚀 其他节点
    type: select
    interval: 86400 
    url: http://www.gstatic.com/generate_204
    
    use:
      - foo5
  - name: 🐟 规则外路由选择
    type: select
    proxies:
      - 🔰 节点选择
      - DIRECT
      - 🇭🇰 香港节点
      - 🇨🇳 台湾节点
      - 🇸🇬 狮城节点
      - 🇯🇵 日本节点
      - 🇺🇲 美国节点
      - 🚀 其他节点
# github Loyalsoldier规则集,合并mix
rule-providers:
  cncidr: #中国大陆 IP 地址列表
   type: http
   behavior: ipcidr
   url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
   path: ./profiles/rules/cncidr.yaml
   interval: 86400
   
  proxy: #代理域名列表 
   type: http
   behavior: domain
   url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
   path: ./profiles/rules/proxy.yaml
   interval: 86400
   
  gfw: #GFWList 域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./profiles/rules/gfw.yaml
    interval: 86400
    
  greatfire: #GreatFire 域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./profiles/rules/greatfire.yaml
    interval: 86400
  reject: #广告 域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./profiles/rules/reject.yaml
    interval: 86400
rules:
 - RULE-SET,reject, REJECT
```

### 日志

```raw
清除当时的日志了，全走reject
```
