### ISSUE TITLE
[BUG] error: unsupported rule type RULE-SET

### ISSUE THREAD

**Issue by lihaoze123** [Kr328/ClashForAndroid#1751]
### 描述此错误

添加配置文件时报错 `error: unsupported rule type RULE-SET`。
`proxy.yaml` 文件和 `ruleset.yaml`  文件均在 “外部资源文件列表” 导入，并重命名为原文件名。

### 配置文件

```yml
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 1.0.0.1
    - 8.8.4.4
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 1.0.0.1
    - 8.8.4.4
  fallback:
    - https://1.1.1.1/dns-query
    - https://doh.dns.sb/dns-query
    - https://public.dns.iij.jp/dns-query
  fallback-filter:
    geoip: true
    domain:
      - '+.desperadoj.com'

proxy-providers:
  NeteaseMusic:
    type: file
    path: ./proxy.yaml

proxy-groups:
  - name: netease
    type: select
    use:
      - NeteaseMusic
    proxies:
      - DIRECT

rule-providers:
  NeteaseMusic:
    type: file
    behavior: classical
    path: ./ruleset.yaml

rules:
  - DOMAIN,admusicpic.music.126.net,REJECT
  - DOMAIN,iadmat.nosdn.127.net,REJECT
  - DOMAIN,iadmusicmat.music.126.net,REJECT
  - DOMAIN,iadmusicmatvideo.music.126.net,REJECT

  - RULE-SET,NeteaseMusic,netease

  - MATCH,DIRECT
```

### 日志

```raw
rules[4] [RULE-SET,NeteaseMusic,netease] error: unsupported rule type RULE-SET
```

### 屏幕截图

![Screenshot_2022-11-21-13-15-13-472_com github kr328 clash foss](https://user-images.githubusercontent.com/35329574/202972231-8f330771-949b-402a-ab59-e901056c390f.jpg)
![Screenshot_2022-11-21-13-15-17-919_com github kr328 clash foss](https://user-images.githubusercontent.com/35329574/202972243-a4c1de91-837f-45d9-a01e-3855938ca3a8.jpg)
![Screenshot_2022-11-21-13-15-21-477_com estrongs android pop](https://user-images.githubusercontent.com/35329574/202972251-f9e687a4-3e56-4cc1-ab29-7aba28462857.jpg)
