### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Airuop** [Kr328/ClashForAndroid#1753]
### Describe the bug

[TCP] dial All (match Match/) to 149.154.xxx.xx:5222 error: dial 130.61.xxx.xx:443 error: x509: cannot validate certificate for 130.61.xxx.xx because it doesn't contain any IP SANs

### To Reproduce

type proxy group : url test
proxy  selected but cannot connect

### Device Info

- Device: honor 8x
- ROM:Emui 9 
- Android Version: 9

### Application Info

- Version: 2.5.12.premium
- APK filename: app-release-arm64-v8a.apk
- Distribution Channel: playstore

### Configure File

```yml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enable: true
  ipv6: true
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
  enhanced-mode: redir-host
  nameserver:
    - tls://one.one.one.one:853
    - tls://dns.google:853
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.adguard.com/dns-query
  fallback:
    - https://azure.cloudflare-dns.com/dns-query
    - https://dns.dnshome.de/dns-query
    - https://dns.hostux.net/dns-query
    - https://NoTMIKE.dev/dns.php
    - https://doh.42l.fr/dns-query
    - https://DNS.HeN.ee/dns-query
    - https://doh.dnswarden.com/uncensored
    - tls://one.one.one.one:853
    - tls://dns.google:853
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.quad9.net/dns-query
    - https://mozilla.cloudflare-dns.com/dns-query
    - https://EU2.DNS.LAVATE.CH/dns-query
    - https://DANDELIONSPROUT.Asuscomm.com:2501/dns-query
    - https://dns.switch.ch/dns-query
    - https://dnsforge.de/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh-de.blahdns.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: IR
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
      - +.gvt1.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.bing.com
  fake-ip-filter:
    - '*.lan'
    - stun.*.*.*
    - stun.*.*
    - time.windows.com
    - time.nist.gov
    - time.apple.com
    - time.asia.apple.com
    - '*.openwrt.pool.ntp.org'
    - pool.ntp.org
    - ntp.ubuntu.com
    - time1.apple.com
    - time2.apple.com
    - time3.apple.com
    - time4.apple.com
    - time5.apple.com
    - time6.apple.com
    - time7.apple.com
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    - api.joox.com
    - joox.com
    - '*.xiami.com'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - '*.*.stun.playstation.net'
    - xbox.*.*.microsoft.com
    - '*.ipv6.microsoft.com'
    - speedtest.cros.wr.pvp.net
proxies:
  - {"type":"ss","name":"default_name","server":"198.57.27.218","port":5,"cipher":"aes-256-gcm","password":"g5MeD6Ft3CWlJId"}
proxy-groups:
  - name: All
    type: select
    proxies:
      - Auto
      - fallback-auto
      - Direct
      - default_name
  - name: Auto
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - default_name
  - name: fallback-auto
    type: fallback
    proxies:
      - default_name
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: Direct
    type: select
    proxies:
      - DIRECT
  - name: BLOCK
    type: select
    proxies:
      - REJECT
rule-providers:
  iran:
    type: http
    behavior: classical
    url: https://....................../clash_rules.yaml
    path: ./ruleset/iran.yaml
    interval: 432000
rules:
  - RULE-SET,iran,Direct
  - GEOIP,IR,Direct
  - DOMAIN-SUFFIX,local,DIRECT
  - MATCH,All
```

### Logs

```raw
[TCP] dial All (match Match/) to 149.154.xxx.xx:5222 error: dial 130.61.xxx.xx:443 error: x509: cannot validate certificate for 130.61.xxx.xx because it doesn't contain any IP SANs
```
