### ISSUE TITLE
[BUG] 更新订阅链接显示权限不足

### ISSUE THREAD

**Issue by RookieTerry** [Kr328/ClashForAndroid#1763]
### 描述此错误

在[两仪](https://github.com/twoyi/twoyi)APP中更新订阅链接时报错：`open /data/user/0/com.github.kr328.clash/files/processing/config.yaml:permission denied `

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:虚拟机
- 系统类型:原生安卓
- Android 版本:8.0

### 应用信息

- 版本:2.5.9-premium
- 安装包文件名:（未知）
- 应用来源:Google Play

### 配置文件

```yml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - https://doh.buzz:8000/dns-query
    - https://doh.beauty:8000/dns-query
    - https://cloudflare-dns.com/dns-query
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - https://dns.google/dns-query
    - https://dns.twnic.tw/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
  nameserver-policy: ~
cfw-bypass:
  - qq.com
  - music.163.com
  - "*.music.126.net"
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 5000
proxies:
  - {name: 馃嚡馃嚨 鍏嶈垂-鏃ユ湰1, server: jp01-vm0.entry.srthdw.art, port: 444, type: vmess, uuid: 0916b955-9cf8-39bc-a28c-ec1714aa67ca, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /hls/cctv5phd.m3u8, headers: {Host: bf419d5f59f96a.windowsupdate.com}}, ws-path: /hls/cctv5phd.m3u8, ws-headers: {Host: bf419d5f59f96a.windowsupdate.com}}
  - {name: 馃嚡馃嚨 鍏嶈垂-鏃ユ湰2, server: jp02-vm0.entry.srthdw.art, port: 444, type: vmess, uuid: 0916b955-9cf8-39bc-a28c-ec1714aa67ca, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /hls/cctv5phd.m3u8, headers: {Host: jp02-vm0.entry.srthdw.art}}, ws-path: /hls/cctv5phd.m3u8, ws-headers: {Host: jp02-vm0.entry.srthdw.art}}
  - {name: 馃嚡馃嚨 鍏嶈垂-鏃ユ湰3, server: jp03-vm0.entry.srthdw.art, port: 444, type: vmess, uuid: 0916b955-9cf8-39bc-a28c-ec1714aa67ca, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /hls/cctv5phd.m3u8, headers: {Host: jp03-vm0.entry.srthdw.art}}, ws-path: /hls/cctv5phd.m3u8, ws-headers: {Host: jp03-vm0.entry.srthdw.art}}
  - {name: 馃嚡馃嚨 鍏嶈垂-鏃ユ湰4, server: jp04-vm0.entry.srthdw.art, port: 444, type: vmess, uuid: 0916b955-9cf8-39bc-a28c-ec1714aa67ca, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /hls/cctv5phd.m3u8, headers: {Host: bf419d5f59f7d0.windowsupdate.com}}, ws-path: /hls/cctv5phd.m3u8, ws-headers: {Host: bf419d5f59f7d0.windowsupdate.com}}
  - {name: 馃嚡馃嚨 鍏嶈垂-鏃ユ湰5, server: jp05-vm0.entry.srthdw.art, port: 444, type: vmess, uuid: 0916b955-9cf8-39bc-a28c-ec1714aa67ca, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /hls/cctv5phd.m3u8, headers: {Host: jp05-vm0.entry.srthdw.art}}, ws-path: /hls/cctv5phd.m3u8, ws-headers: {Host: jp05-vm0.entry.srthdw.art}}
  - {name: 馃嚡馃嚨 鍏嶈垂-鏃ユ湰6, server: jp06-vm0.entry.srthdw.art, port: 444, type: vmess, uuid: 0916b955-9cf8-39bc-a28c-ec1714aa67ca, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /hls/cctv5phd.m3u8, headers: {Host: jp06-vm0.entry.srthdw.art}}, ws-path: /hls/cctv5phd.m3u8, ws-headers: {Host: jp06-vm0.entry.srthdw.art}}
proxy-groups:
  - name: 馃敯 閫夋嫨鑺傜偣
    type: select
    proxies:
      - 馃嚡馃嚨 鍏嶈垂-鏃ユ湰1
      - 馃嚡馃嚨 鍏嶈垂-鏃ユ湰2
      - 馃嚡馃嚨 鍏嶈垂-鏃ユ湰3
      - 馃嚡馃嚨 鍏嶈垂-鏃ユ湰4
      - 馃嚡馃嚨 鍏嶈垂-鏃ユ湰5
      - 馃嚡馃嚨 鍏嶈垂-鏃ユ湰6
      - DIRECT
  - name: 馃審 鐖卞鑹?鍝斿摡鍝斿摡
    type: select
    proxies:
      - DIRECT
  - name: 馃摵 鍔ㄧ敾鐤?    type: select
    proxies:
      - 馃敯 閫夋嫨鑺傜偣
      - DIRECT
  - name: 馃幃 Steam
    type: select
    proxies:
      - 馃敯 閫夋嫨鑺傜偣
      - DIRECT
  - name: 馃幃 Steam濂藉弸
    type: select
    proxies:
      - DIRECT
      - 馃敯 閫夋嫨鑺傜偣
  - name: 馃柤锔?Pixiv
    type: select
    proxies:
      - 馃敯 閫夋嫨鑺傜偣
      - DIRECT
  - name: 馃惣 ExHentai
    type: select
    proxies:
      - 馃敯 閫夋嫨鑺傜偣
      - DIRECT
  - name: 鈽侊笍 Cloudflare
    type: select
    proxies:
      - 馃敯 閫夋嫨鑺傜偣
      - 馃悷 婕忕綉涔嬮奔
      - DIRECT
  - name: 馃嚚馃嚦 鍥藉唴缃戠珯
    type: select
    proxies:
      - DIRECT
      - 馃敯 閫夋嫨鑺傜偣
  - name: 馃洃 鎷︽埅骞垮憡
    type: select
    proxies:
      - REJECT
      - DIRECT
      - 馃敯 閫夋嫨鑺傜偣
  - name: 馃悷 婕忕綉涔嬮奔
    type: select
    proxies:
      - 馃敯 閫夋嫨鑺傜偣
      - DIRECT
rules:
 - IP-CIDR,103.151.150.0/23,馃審 鐖卞鑹?鍝斿摡鍝斿摡
 - DOMAIN,app.biliapi.net,馃審 鐖卞鑹?鍝斿摡鍝斿摡
 - DOMAIN,grpc.biliapi.net,馃審 鐖卞鑹?鍝斿摡鍝斿摡
 - DOMAIN,p-bstarstatic.akamaized.net,馃審 鐖卞鑹?鍝斿摡鍝斿摡
 - DOMAIN,p.bstarstatic.com,馃審 鐖卞鑹?鍝斿摡鍝斿摡
 - DOMAIN,upos-bstar-mirrorakam.akamaized.net,馃審 鐖卞鑹?鍝斿摡鍝斿摡
```

### 日志

```raw
日志在虚拟安卓机中，无法导出
```
