### ISSUE TITLE
[BUG] 问题更新（对 #1483 问题的补充）：切换配置 / 切换模式时所有节点会自动测延迟，但点击启动时只有 server 为 ip 的节点会自动测延迟，server 为域名的节点不会

### ISSUE THREAD

**Issue by zsokami** [Kr328/ClashForAndroid#1764]
### 描述此错误

切换配置 / 切换模式时所有节点会自动测延迟，并自动选择可用节点，但点击启动和点击下面快捷键启动时只有 server 为 ip 的节点会自动测延迟，server 为域名的节点不会，假如所有节点都是域名，则都不会测延迟，不会自动选择可用节点，那这个快捷键也失去意义

![image](https://user-images.githubusercontent.com/57834527/205028054-82833f5e-0afc-49f7-82cc-4d4065e41f1a.png)

### 如何复现该错误

步骤 1: 启动
步骤 2: 稍等片刻，点击代理查看延迟
步骤 3: 关闭
重复以上步骤几次

### 设备信息

- 机型: MI 5X
- 系统类型: MIUI 10 9.1.24 | 开发版
- Android 版本: 8.1.0

### 应用信息

- 版本: 2.5.12.premium
- 安装包文件名: cfa-2.5.12-premium-arm64-v8a-release.apk
- 应用来源: Github

### 配置文件

```yml
mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: :9090
proxies:
  - ip 节点
  - 域名节点
proxy-groups:
  - name: ✈️ ‍起飞
    type: select
    proxies:
      - ⚡ ‍低延迟
      - 👆🏻 ‍指定
      - DIRECT
  - name: ⚡ ‍低延迟
    type: url-test
    tolerance: 50
    interval: 30
    url: https://i.ytimg.com/generate_204
    proxies:
      - ip 节点
      - 域名节点
  - name: 👆🏻 ‍指定
    type: select
    proxies:
      - ip 节点
      - 域名节点
rules:
 - MATCH,✈️ ‍起飞
```
