### ISSUE TITLE
[BUG] IPv6代理问题

### ISSUE THREAD

**Issue by XhL6996** [Kr328/ClashForAndroid#1804]
### 描述此错误

配置文件中开启了IPv6代理及IPv6的DNS解析，可以正常访问IPv6网页，但使用SSH工具连接IPv6云服务器时，出现“目的不可达”报错（节点支持IPv6，v2rayNG可以成功连接）。

### 如何复现该错误

步骤 1: 配置文件中开启IPv6和IPv6 DNS解析
步骤 2: 启动CFA
步骤 3: 使用SSH工具连接IPv6云服务器

### 设备信息

- 机型: Redmi K40
- 系统类型: MIUI 14
- Android 版本: 13

### 应用信息

- 版本: 2.5.12.premium
- 安装包文件名: cfa-2.5.12-premium-universal-release.apk
- 应用来源: Github

### 配置文件

```yml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
ipv6: true
dns:
  enable: true
  enhanced-mode: redir-host
  ipv6: true
  nameserver:
  - tls://223.5.5.5
  - tls://1.12.12.12
  fallback:
  - tls://1.1.1.1
  - tls://8.8.8.8
```

### 日志

```raw
捕获的日志中无法找到相关（到IPv6云服务器22端口）连接。
```

### 屏幕截图

分别是使用Termius和Juice SSH的截图：
![IMG_20230114_223238](https://user-images.githubusercontent.com/63577165/212477099-7b657b3e-597a-4c81-b6f1-4fd7e0e77ad3.jpg)
![Screenshot_2023-01-14-22-31-34-128_com sonelli juicessh-edit](https://user-images.githubusercontent.com/63577165/212477103-a241455e-20f2-483e-b6d2-06f4fcf002d6.jpg)
