### ISSUE TITLE
[BUG] 订阅链接报错 tls: server chose an unconfigured cipher suite

### ISSUE THREAD

**Issue by miyouzi** [Kr328/ClashForAndroid#1806]
### 描述此错误

该配置是经过 subconverter 转换后的订阅，通过 nginx 反代套上 SSL，PC端Clash订阅无异常，手机Chrome浏览器无异常，手机Clash订阅报 `tls: server chose an unconfigured cipher suite`

**nginx ssl 相关配置**
```nginx
       listen 443 ssl;
        listen [::]:443 ssl;
        server_name *** ;
        index index.html index.htm index.php default.html default.htm default.php;
        root  /home/wwwroot/***;
        ssl_certificate /etc/letsencrypt/live/***/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/***/privkey.pem; # managed by Certbot
        ssl_session_timeout 5m;
        # ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        # ssl_prefer_server_ciphers on;
        # ssl_ciphers "TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-AES-128-CCM-8-SHA256:TLS13-AES-128-CCM-SHA256:EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5";

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers [EECDH+ECDSA+AESGCM+AES128|EECDH+ECDSA+CHACHA20]:EECDH+ECDSA+AESGCM+AES256:EECDH+ECDSA+AES128+SHA:EECDH+ECDSA+AES256+SHA:[EECDH+aRSA+AESGCM+AES128|EECDH+aRSA+CHACHA20]:EECDH+aRSA+AESGCM+AES256:EECDH+aRSA+AES128+SHA:EECDH+aRSA+AES256+SHA;

        # ssl_session_cache builtin:1000 shared:SSL:10m;
```

### 如何复现该错误

步骤 1: 填入 subconverter 订阅链接
步骤 2: 点击保存报错

### 设备信息

- 机型: 华为 P40 Pro
- 系统类型: 鸿蒙3.0 （安卓12）
- Android 版本: 12

### 应用信息

- 版本: v2.5.12-premium
- 安装包文件名: [cfa-2.5.12-premium-arm64-v8a-release.apk](https://github.com/Kr328/ClashForAndroid/releases/download/v2.5.12/cfa-2.5.12-premium-arm64-v8a-release.apk)
- 应用来源:  Github Releases
 

### 配置文件

```yml
mixed-port: 7890
allow-lan: false
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
proxies:
  - ***
proxy-groups:
  - name: 🧭Final
    type: select
    proxies:
      - 🌑Proxy
      - 🌐Direct
  - name: 🌑Proxy
    type: select
    proxies:
      - 🕹AutoTest
      - 🧯Fallback
      - HK-test
      - TW-test
      - JP-test
      - US-test
      - 🇨🇳 台湾 01 HiNet
      - 🇨🇳 台湾 02 HiNet
      - 🇯🇵 日本 01 电信/沪日专线（3x）
      - 🇯🇵 日本 02 电信/沪日专线（3x）
      - 🇯🇵 日本 05 NTT IPv6
      - 🇯🇵 日本 06 M247 IPv6
      - 🇯🇵 日本 07 IIJ
      - 🇯🇵 日本 09 IIJ
      - 🇯🇵 日本 11 IIJ IPv6
      - 🇯🇵 日本 13 IIJ IPv6
      - 🇯🇵 日本 15 IIJ
      - 🇯🇵 日本 17 IIJ
      - 🇯🇵 日本 19 IIJ
      - 🇯🇵 日本 21 NTT
      - 🇺🇸 美国 01 GIA CN2 IPv6
      - 🇺🇸 美国 03 GIA CN2 IPv6
      - 🇺🇸 美国 05 Cogent IPv6（流媒体）
      - 🇭🇰 香港 01 电信/深港专线（2.5x）
      - 🇭🇰 香港 02 电信/深港专线（2.5x）
      - 🇭🇰 香港 09 HKT商宽（0.1x）
      - 🇭🇰 香港 10 HKT家宽（0.1x）
      - 🇭🇰 香港 11 HKBN家宽（0.1x）
      - 🇭🇰 香港 12 NTT IPv6
      - 🇭🇰 香港 13 Cogent IPv6（流媒体）
      - 🇭🇰 中港专线 IPLC E13 1000Mbps
  - name: HK-test
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 🇭🇰 香港 01 电信/深港专线（2.5x）
      - 🇭🇰 香港 02 电信/深港专线（2.5x）
      - 🇭🇰 香港 09 HKT商宽（0.1x）
      - 🇭🇰 香港 10 HKT家宽（0.1x）
      - 🇭🇰 香港 11 HKBN家宽（0.1x）
      - 🇭🇰 香港 12 NTT IPv6
      - 🇭🇰 香港 13 Cogent IPv6（流媒体）
      - 🇭🇰 中港专线 IPLC E13 1000Mbps
  - name: TW-test
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 400
    proxies:
      - 🇨🇳 台湾 01 HiNet
      - 🇨🇳 台湾 02 HiNet
  - name: JP-test
    type: url-test
    url: https://ecchi.iwara.tv/sites/all/themes/main/img/logo.png
    interval: 600
    proxies:
      - 🇯🇵 日本 01 电信/沪日专线（3x）
      - 🇯🇵 日本 02 电信/沪日专线（3x）
      - 🇯🇵 日本 05 NTT IPv6
      - 🇯🇵 日本 06 M247 IPv6
      - 🇯🇵 日本 07 IIJ
      - 🇯🇵 日本 09 IIJ
      - 🇯🇵 日本 11 IIJ IPv6
      - 🇯🇵 日本 13 IIJ IPv6
      - 🇯🇵 日本 15 IIJ
      - 🇯🇵 日本 17 IIJ
      - 🇯🇵 日本 19 IIJ
      - 🇯🇵 日本 21 NTT
  - name: US-test
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 600
    proxies:
      - 🇺🇸 美国 01 GIA CN2 IPv6
      - 🇺🇸 美国 03 GIA CN2 IPv6
      - 🇺🇸 美国 05 Cogent IPv6（流媒体）
  - name: IPv6-test
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 🇯🇵 日本 05 NTT IPv6
      - 🇯🇵 日本 06 M247 IPv6
      - 🇯🇵 日本 11 IIJ IPv6
      - 🇯🇵 日本 13 IIJ IPv6
      - 🇺🇸 美国 01 GIA CN2 IPv6
      - 🇺🇸 美国 03 GIA CN2 IPv6
      - 🇺🇸 美国 05 Cogent IPv6（流媒体）
      - 🇭🇰 香港 12 NTT IPv6
      - 🇭🇰 香港 13 Cogent IPv6（流媒体）
  - name: RegionFallback
    type: select
    proxies:
      - ⛔️Reject
      - 🌐Direct
      - 🌑Proxy
      - HK-test
      - TW-test
      - JP-test
      - US-test
      - 🇨🇳 台湾 01 HiNet
      - 🇨🇳 台湾 02 HiNet
      - 🇯🇵 日本 01 电信/沪日专线（3x）
      - 🇯🇵 日本 02 电信/沪日专线（3x）
      - 🇯🇵 日本 05 NTT IPv6
      - 🇯🇵 日本 06 M247 IPv6
      - 🇯🇵 日本 07 IIJ
      - 🇯🇵 日本 09 IIJ
      - 🇯🇵 日本 11 IIJ IPv6
      - 🇯🇵 日本 13 IIJ IPv6
      - 🇯🇵 日本 15 IIJ
      - 🇯🇵 日本 17 IIJ
      - 🇯🇵 日本 19 IIJ
      - 🇯🇵 日本 21 NTT
      - 🇺🇸 美国 01 GIA CN2 IPv6
      - 🇺🇸 美国 03 GIA CN2 IPv6
      - 🇺🇸 美国 05 Cogent IPv6（流媒体）
      - 🇭🇰 香港 01 电信/深港专线（2.5x）
      - 🇭🇰 香港 02 电信/深港专线（2.5x）
      - 🇭🇰 香港 09 HKT商宽（0.1x）
      - 🇭🇰 香港 10 HKT家宽（0.1x）
      - 🇭🇰 香港 11 HKBN家宽（0.1x）
      - 🇭🇰 香港 12 NTT IPv6
      - 🇭🇰 香港 13 Cogent IPv6（流媒体）
      - 🇭🇰 中港专线 IPLC E13 1000Mbps
  - name: HK
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 900
    proxies:
      - HK-test
      - RegionFallback
  - name: TW
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 900
    proxies:
      - TW-test
      - RegionFallback
  - name: JP
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 900
    proxies:
      - JP-test
      - RegionFallback
  - name: US
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 900
    proxies:
      - US-test
      - RegionFallback
  - name: IPv6
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 900
    proxies:
      - IPv6-test
      - RegionFallback
  - name: 🎞Streaming
    type: select
    proxies:
      - 🌑Proxy
      - 🕹AutoTest
      - 🇨🇳 台湾 01 HiNet
      - 🇨🇳 台湾 02 HiNet
      - 🇯🇵 日本 01 电信/沪日专线（3x）
      - 🇯🇵 日本 02 电信/沪日专线（3x）
      - 🇯🇵 日本 05 NTT IPv6
      - 🇯🇵 日本 06 M247 IPv6
      - 🇯🇵 日本 07 IIJ
      - 🇯🇵 日本 09 IIJ
      - 🇯🇵 日本 11 IIJ IPv6
      - 🇯🇵 日本 13 IIJ IPv6
      - 🇯🇵 日本 15 IIJ
      - 🇯🇵 日本 17 IIJ
      - 🇯🇵 日本 19 IIJ
      - 🇯🇵 日本 21 NTT
      - 🇺🇸 美国 01 GIA CN2 IPv6
      - 🇺🇸 美国 03 GIA CN2 IPv6
      - 🇺🇸 美国 05 Cogent IPv6（流媒体）
      - 🇭🇰 香港 01 电信/深港专线（2.5x）
      - 🇭🇰 香港 02 电信/深港专线（2.5x）
      - 🇭🇰 香港 09 HKT商宽（0.1x）
      - 🇭🇰 香港 10 HKT家宽（0.1x）
      - 🇭🇰 香港 11 HKBN家宽（0.1x）
      - 🇭🇰 香港 12 NTT IPv6
      - 🇭🇰 香港 13 Cogent IPv6（流媒体）
      - 🇭🇰 中港专线 IPLC E13 1000Mbps
  - name: 🎞StreamingSE
    type: select
    proxies:
      - 🌐Direct
      - 🇨🇳 台湾 01 HiNet
      - 🇨🇳 台湾 02 HiNet
      - 🇯🇵 日本 01 电信/沪日专线（3x）
      - 🇯🇵 日本 02 电信/沪日专线（3x）
      - 🇯🇵 日本 05 NTT IPv6
      - 🇯🇵 日本 06 M247 IPv6
      - 🇯🇵 日本 07 IIJ
      - 🇯🇵 日本 09 IIJ
      - 🇯🇵 日本 11 IIJ IPv6
      - 🇯🇵 日本 13 IIJ IPv6
      - 🇯🇵 日本 15 IIJ
      - 🇯🇵 日本 17 IIJ
      - 🇯🇵 日本 19 IIJ
      - 🇯🇵 日本 21 NTT
      - 🇺🇸 美国 01 GIA CN2 IPv6
      - 🇺🇸 美国 03 GIA CN2 IPv6
      - 🇺🇸 美国 05 Cogent IPv6（流媒体）
      - 🇭🇰 香港 01 电信/深港专线（2.5x）
      - 🇭🇰 香港 02 电信/深港专线（2.5x）
      - 🇭🇰 香港 09 HKT商宽（0.1x）
      - 🇭🇰 香港 10 HKT家宽（0.1x）
      - 🇭🇰 香港 11 HKBN家宽（0.1x）
      - 🇭🇰 香港 12 NTT IPv6
      - 🇭🇰 香港 13 Cogent IPv6（流媒体）
      - 🇭🇰 中港专线 IPLC E13 1000Mbps
  - name: 🛡Guard
    type: select
    proxies:
      - ⛔️Reject
      - 🌐Direct
  - name: 🧯Fallback
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 🇨🇳 台湾 01 HiNet
      - 🇨🇳 台湾 02 HiNet
      - 🇯🇵 日本 01 电信/沪日专线（3x）
      - 🇯🇵 日本 02 电信/沪日专线（3x）
      - 🇯🇵 日本 05 NTT IPv6
      - 🇯🇵 日本 06 M247 IPv6
      - 🇯🇵 日本 07 IIJ
      - 🇯🇵 日本 09 IIJ
      - 🇯🇵 日本 11 IIJ IPv6
      - 🇯🇵 日本 13 IIJ IPv6
      - 🇯🇵 日本 15 IIJ
      - 🇯🇵 日本 17 IIJ
      - 🇯🇵 日本 19 IIJ
      - 🇯🇵 日本 21 NTT
      - 🇺🇸 美国 01 GIA CN2 IPv6
      - 🇺🇸 美国 03 GIA CN2 IPv6
      - 🇺🇸 美国 05 Cogent IPv6（流媒体）
      - 🇭🇰 香港 01 电信/深港专线（2.5x）
      - 🇭🇰 香港 02 电信/深港专线（2.5x）
      - 🇭🇰 香港 09 HKT商宽（0.1x）
      - 🇭🇰 香港 10 HKT家宽（0.1x）
      - 🇭🇰 香港 11 HKBN家宽（0.1x）
      - 🇭🇰 香港 12 NTT IPv6
      - 🇭🇰 香港 13 Cogent IPv6（流媒体）
      - 🇭🇰 中港专线 IPLC E13 1000Mbps
  - name: 🕹AutoTest
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 🇨🇳 台湾 01 HiNet
      - 🇨🇳 台湾 02 HiNet
      - 🇯🇵 日本 01 电信/沪日专线（3x）
      - 🇯🇵 日本 02 电信/沪日专线（3x）
      - 🇯🇵 日本 05 NTT IPv6
      - 🇯🇵 日本 06 M247 IPv6
      - 🇯🇵 日本 07 IIJ
      - 🇯🇵 日本 09 IIJ
      - 🇯🇵 日本 11 IIJ IPv6
      - 🇯🇵 日本 13 IIJ IPv6
      - 🇯🇵 日本 15 IIJ
      - 🇯🇵 日本 17 IIJ
      - 🇯🇵 日本 19 IIJ
      - 🇯🇵 日本 21 NTT
      - 🇺🇸 美国 01 GIA CN2 IPv6
      - 🇺🇸 美国 03 GIA CN2 IPv6
      - 🇺🇸 美国 05 Cogent IPv6（流媒体）
      - 🇭🇰 香港 01 电信/深港专线（2.5x）
      - 🇭🇰 香港 02 电信/深港专线（2.5x）
      - 🇭🇰 香港 09 HKT商宽（0.1x）
      - 🇭🇰 香港 10 HKT家宽（0.1x）
      - 🇭🇰 香港 11 HKBN家宽（0.1x）
      - 🇭🇰 香港 12 NTT IPv6
      - 🇭🇰 香港 13 Cogent IPv6（流媒体）
      - 🇭🇰 中港专线 IPLC E13 1000Mbps
  - name: ⛔️Reject
    type: select
    proxies:
      - REJECT
  - name: 🌐Direct
    type: select
    proxies:
      - DIRECT
rules:
 - 过长此处省略
```

### 日志

```raw
配置无法保存，应用内的 Logcat 不适用
```

### 屏幕截图

**报错界面：**
![image](https://user-images.githubusercontent.com/24269465/214026001-4603aa36-95ae-4629-a94a-926f46076c3d.png)

**手机Chrome浏览器直接访问无异常**
![image](https://user-images.githubusercontent.com/24269465/214026466-f6edd989-3bb5-44f7-a084-66221ee2b87d.png)
