### ISSUE TITLE
[BUG] 手工导入配置文件，编辑保存后，自动把最后一行的一部分内容复制2次，生成了新的一行

### ISSUE THREAD

**Issue by zhychen1173** [Kr328/ClashForAndroid#1835]
### 描述此错误

我导入配置文件，编辑保存，被提示 proxy 🐟 漏网之鱼🐟 漏网之鱼  不存在，我检查之后，发现配置文件最后多出来一行 🐟 漏网之鱼。
删除此行后再次保存，又发生同样的提示，进去再次发现配置文件最后又多出来了这行。
尝试多次都是如此。
我配置文件的最后一行原来的内容是：
 - MATCH,🐟 漏网之鱼

### 如何复现该错误

步骤 1: 导入原来电脑端的配置文件
步骤 2: 修改保存。被提示  proxy 🐟 漏网之鱼🐟 漏网之鱼  不存在
步骤 3: 检查发现配置文件后面多出来一行新的内容：   🐟 漏网之鱼🐟 漏网之鱼 
步骤 4: 将最后一行删除，保存，再次出现相同提示。
步骤 4: 检查发现配置文件后面多出来一行新的内容：   🐟 漏网之鱼🐟 漏网之鱼 
步骤5：尝试多次重新修改保存，均出现上述情况。
...

### 设备信息

- 机型:小米11 pro
- 系统类型: MIUI 13.0.13
- Android 版本: 12

### 应用信息

- 版本:2.5.12
- 安装包文件名: [cfa-2.5.12-premium-arm64-v8a-release.apk](https://github.com/Kr328/ClashForAndroid/releases/download/v2.5.12/cfa-2.5.12-premium-arm64-v8a-release.apk)
- 应用来源: google play 

### 配置文件

```yml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies: 
 
proxy-providers:

  

proxy-groups:

  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 常规中转
      - ♻️ 临时高倍率中转
      - ♻️ 常规计费机场
      - ♻️ 高倍率机场
      - ♻️ 你的VPS
      - DIRECT

  - name: ♻️ 常规中转
    type: relay
    proxies:
      - ♻️ 常规计费机场
      - ♻️ 你的VPS

  - name: ♻️ 临时高倍率中转
    type: relay
    proxies:
      - ♻️ 高倍率机场
      - ♻️ 你的VPS

  - name: ♻️ 你的机场
    type: select
    use:
      - Jichang

  - name: ♻️ 你的VPS
    type: select
    use:
      - Vps

  - name: ♻️ 常规计费机场
    type: url-test
    tolerance: 100
    use:
      - 常规机场

  - name: ♻️ 高倍率机场
    type: url-test
    tolerance: 100
    use:
      - 高倍机场


  - name: 🌍 国外媒体
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 常规中转
      - 🎯 全球直连
  - name: 📲 电报信息
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择
  - name: 🍎 苹果服务
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
  - name: 📢 谷歌FCM
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - ♻️ 常规中转
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - ♻️ 常规中转
  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🍃 应用净化
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - ♻️ 常规中转
rules:
 - DOMAIN-SUFFIX,acl4.ssr,🎯 全球直连
 - DOMAIN-SUFFIX,ip6-localhost,🎯 全球直连
 - DOMAIN-SUFFIX,ip6-loopback,🎯 全球直连
 - DOMAIN-SUFFIX,lan,🎯 全球直连
 - IP-CIDR,116.66.184.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,116.71.96.0/20,🎯 全球直连,no-resolve
 - IP-CIDR,116.71.128.0/21,🎯 全球直连,no-resolve
 - IP-CIDR,116.71.136.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,116.71.141.0/24,🎯 全球直连,no-resolve
 - IP-CIDR,116.71.142.0/24,🎯 全球直连,no-resolve
 - IP-CIDR,116.71.243.0/24,🎯 全球直连,no-resolve
 - IP-CIDR,116.71.244.0/24,🎯 全球直连,no-resolve
 - IP-CIDR,116.71.251.0/24,🎯 全球直连,no-resolve
 - IP-CIDR,117.78.0.0/18,🎯 全球直连,no-resolve
 - IP-CIDR,119.3.0.0/16,🎯 全球直连,no-resolve
 - IP-CIDR,119.8.0.0/21,🎯 全球直连,no-resolve
 - IP-CIDR,119.8.32.0/19,🎯 全球直连,no-resolve
 - IP-CIDR,121.36.0.0/17,🎯 全球直连,no-resolve
 - IP-CIDR,121.36.128.0/18,🎯 全球直连,no-resolve
 - IP-CIDR,121.37.0.0/17,🎯 全球直连,no-resolve
 - IP-CIDR,122.112.128.0/17,🎯 全球直连,no-resolve
 - IP-CIDR,139.9.0.0/18,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.12.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.18.0/23,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.24.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.28.0/23,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.38.0/23,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.40.0/23,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.44.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.48.0/21,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.128.0/21,🎯 全球直连,no-resolve
 - IP-CIDR,103.74.24.0/21,🎯 全球直连,no-resolve
 - IP-CIDR,103.74.48.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.126.92.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.129.252.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.131.252.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.135.240.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.196.64.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,106.2.32.0/19,🎯 全球直连,no-resolve
 - IP-CIDR,106.2.64.0/18,🎯 全球直连,no-resolve
 - IP-CIDR,114.113.196.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,114.113.200.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,115.236.112.0/20,🎯 全球直连,no-resolve
 - IP-CIDR,115.238.76.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,123.58.160.0/19,🎯 全球直连,no-resolve
 - IP-CIDR,223.252.192.0/19,🎯 全球直连,no-resolve
 - IP-CIDR,101.198.128.0/18,🎯 全球直连,no-resolve
 - IP-CIDR,101.198.192.0/19,🎯 全球直连,no-resolve
 - IP-CIDR,101.199.196.0/22,🎯 全球直连,no-resolve
 - GEOIP,CN,🎯 全球直连
 - MATCH,🐟 漏网之鱼
```

### 日志

```raw
没有日志。
```

### 屏幕截图

![dd5db6b2886aad2287287f8be22720f](https://user-images.githubusercontent.com/117578752/221169348-84191557-a725-4bba-a9e9-a069afd512e4.jpg)
