### ISSUE TITLE
[BUG] nplayer webdav ipv6链接失败

### ISSUE THREAD

**Issue by alonginwind** [Kr328/ClashForAndroid#1868]
### 描述此错误

关闭clash，nplayer webdav 用ipv6链接正常。
开启clash，连接失败; 覆写中开启ipv6，仍然链接失败。

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型:小米11
- 系统类型:miui14
- Android 版本:13

### 应用信息

- 版本:2.5.12-premium
- 安装包文件名:cfa-2.5.12-premium-arm64-v8a-release.apk
- 应用来源:github

### 配置文件

```yml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:8853
  enhanced-mode: fake-ip
  nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://doh.pub/dns-query
  fake-ip-filter:
    - "*.lan"
    - stun.*.*.*
    - stun.*.*
    - time.windows.com
    - time.nist.gov
    - time.apple.com
    - time.asia.apple.com
    - "*.ntp.org.cn"
    - "*.openwrt.pool.ntp.org"
    - time1.cloud.tencent.com
    - time.ustc.edu.cn
    - pool.ntp.org
    - ntp.ubuntu.com
    - ntp.aliyun.com
    - ntp1.aliyun.com
    - ntp2.aliyun.com
    - ntp3.aliyun.com
    - ntp4.aliyun.com
    - ntp5.aliyun.com
    - ntp6.aliyun.com
    - ntp7.aliyun.com
    - time1.aliyun.com
    - time2.aliyun.com
    - time3.aliyun.com
    - time4.aliyun.com
    - time5.aliyun.com
    - time6.aliyun.com
    - time7.aliyun.com
    - "*.time.edu.cn"
    - time1.apple.com
    - time2.apple.com
    - time3.apple.com
    - time4.apple.com
    - time5.apple.com
    - time6.apple.com
    - time7.apple.com
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - localhost.ptlogin2.qq.com
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.ipv6.microsoft.com"
    - "*.*.xboxlive.com"
    - speedtest.cros.wr.pvp.net

- IP-CIDR,103.72.12.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.18.0/23,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.24.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.28.0/23,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.38.0/23,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.40.0/23,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.44.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.48.0/21,🎯 全球直连,no-resolve
 - IP-CIDR,103.72.128.0/21,🎯 全球直连,no-resolve
 - IP-CIDR,103.74.24.0/21,🎯 全球直连,no-resolve
 - IP-CIDR,103.74.48.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.126.92.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.129.252.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.131.252.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.135.240.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,103.196.64.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,106.2.32.0/19,🎯 全球直连,no-resolve
 - IP-CIDR,106.2.64.0/18,🎯 全球直连,no-resolve
 - IP-CIDR,114.113.196.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,114.113.200.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,115.236.112.0/20,🎯 全球直连,no-resolve
 - IP-CIDR,115.238.76.0/22,🎯 全球直连,no-resolve
 - IP-CIDR,123.58.160.0/19,🎯 全球直连,no-resolve
 - IP-CIDR,223.252.192.0/19,🎯 全球直连,no-resolve
 - IP-CIDR,101.198.128.0/18,🎯 全球直连,no-resolve
 - IP-CIDR,101.198.192.0/19,🎯 全球直连,no-resolve
 - IP-CIDR,101.199.196.0/22,🎯 全球直连,no-resolve
 - GEOIP,CN,🎯 全球直连
 - MATCH,🐟 漏网之鱼
```

### 日志

```raw
logcat无法捕获日志
```
