### ISSUE TITLE
[BUG] 网络->『系统代理「为 VpnService 附加 HTTP 代理」』开启导致错误

### ISSUE THREAD

**Issue by rule-airport** [Kr328/ClashForAndroid#1874]
### 描述此错误

- 点开按钮后
   - 京东图片资源加载缓慢，YouTube 加载速度正常很快；但是，部分软件（咸鱼、知乎等）通知被拒绝，无法正确通知
- 关闭按钮后
  - 这个按钮点开后京东图片资源加载正常了，YouTube 的视频的封面加载慢了；部分软件（咸鱼、知乎等）通知正常了

### 如何复现该错误

点开，关闭就可以复现了

### 设备信息

- 机型: xiaomi 13
- 系统类型: miui 14
- Android 版本: 13

### 应用信息

- 版本: v2.5.12-premium
- 安装包文件名: cfa-2.5.12-premium-x86-release.apk
- 应用来源: GitHub

### 配置文件

```yml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - https://doh.pub/dns-query
rules:
 - DOMAIN,0azx1.com,REJECT
 - DOMAIN,0b6e714203b6797e8d4.com,REJECT
 - DOMAIN,0b9d84d93f1b.com,REJECT
 - DOMAIN,0c8a10b46fc6.com,REJECT
 - DOMAIN,0ci.top,REJECT
 - DOMAIN,0d847862199.com,REJECT
 - DOMAIN,0dbcf515975d.com,REJECT
 - DOMAIN,0e6fc55ed3d4c2c2ba0.com,REJECT
 - DOMAIN,0emm.com,REJECT
 - DOMAIN,0emn.com,REJECT
 - DOMAIN,0f461325bf56c3e1b9.com,REJECT
 - DOMAIN,0fmm.com,REJECT
 - DOMAIN,0gctp5ht.top,REJECT
 - DOMAIN,0gw7e6s3wrao9y3q.pro,REJECT
 - DOMAIN,0icep80f.com,REJECT
 - DOMAIN,0j7z9aw6.top,REJECT
 - DOMAIN,0ka.com,REJECT
 - DOMAIN,0koryu0.easter.ne.jp,REJECT
 - DOMAIN,0llii0g6.com,REJECT
 - DOMAIN,0nso0tq1sa4.ml,REJECT
 - DOMAIN,0o.868iy.cn,REJECT
 - DOMAIN,0pixl.com,REJECT
 - DOMAIN,0ql3xxre2h.com,REJECT
 - DOMAIN,0stats.com,REJECT
 - DOMAIN,0x5.me,REJECT
 - DOMAIN,0xiaoshuo.com,REJECT
 - DOMAIN,1-cl0ud.com,REJECT
 - DOMAIN,1.5646.cn,REJECT
 - DOMAIN,1.allyes.com.cn,REJECT
 - DOMAIN,1.cn716.com,REJECT
 - DOMAIN,1.dwx365.com,REJECT
 - DOMAIN,1.feeddsp.cn,REJECT
 - DOMAIN,1.guyaheng.com,REJECT
 - DOMAIN,1.huilv.cc,REJECT
 - DOMAIN,1.huobiwang.cc,REJECT
 - DOMAIN,1.hysou.com,REJECT
 - DOMAIN,1.proewildfire.cn,REJECT
 - DOMAIN,1.qt86.com,REJECT
 - DOMAIN,1.tongquee.com,REJECT
 - DOMAIN,1.wosoni.com,REJECT
 - DOMAIN,1.xspic.com,REJECT
 - DOMAIN,1.ytelc.com,REJECT
 - DOMAIN,100669.com,REJECT
 - DOMAIN,100cpc.com,REJECT
 - DOMAIN,100widgets.com,REJECT
 - DOMAIN,101m3.com,REJECT
 - DOMAIN,1024mzs.pw,REJECT
 - DOMAIN,103092804.com,REJECT
 - DOMAIN,103bees.com,REJECT
 - DOMAIN,105app.com,REJECT
 - DOMAIN,109-204-26-16.netconnexion.managedbroadband.co.uk,REJECT
 - DOMAIN,10a053584f01fcaeab1.com,REJECT
 - DOMAIN,10b883b3d61d.com,REJECT
 - DOMAIN,10fbb07a4b0.se,REJECT
 - DOMAIN,10y5gehv.com,REJECT
 - DOMAIN,1100i.com,REJECT
 - DOMAIN,110160.com,REJECT
 - DOMAIN,110380d053f716c4.com,REJECT
 - DOMAIN,111ol.111ol.com,REJECT
 - DOMAIN,111ol.com,REJECT
 - DOMAIN,114lm.com,REJECT
 - DOMAIN,114park.com,REJECT
 - DOMAIN,114study.adsame.com,REJECT
 - DOMAIN,114yeah.com,REJECT
 - DOMAIN,11599jgj.com,REJECT
 - DOMAIN,116b.com,REJECT
 - DOMAIN,118114.cn,REJECT
 - DOMAIN,1188.com,REJECT
 - DOMAIN,11888vip.cn,REJECT
 - DOMAIN,118aa629a7968e75e.com,REJECT
 - DOMAIN,11hrcnll.com,REJECT
 - DOMAIN,11nux.com,REJECT
 - DOMAIN,1221e236c3f8703.com,REJECT
 - DOMAIN,12291.com,REJECT
 - DOMAIN,123-counter.de,REJECT
 - DOMAIN,123.ydylwang.net,REJECT
 - DOMAIN,1234.zgxue.com,REJECT
 - DOMAIN,123advertising.nl,REJECT
 - DOMAIN,123compteur.com,REJECT
 - DOMAIN,123count.com,REJECT
 - DOMAIN,123cursors.com,REJECT
 - DOMAIN,123date.me,REJECT
 - DOMAIN,123vidz.com,REJECT
 - DOMAIN,12648afd00d93.com,REJECT
 - DOMAIN,1298bab69bbc4.com,REJECT
 - DOMAIN,12dc71b7cb820f2a.com,REJECT
 - DOMAIN,12i.cn,REJECT
 - DOMAIN,12l22.net,REJECT
 - DOMAIN,12mnkys.com,REJECT
 - DOMAIN,12place.com,REJECT
 - DOMAIN,12wd87h.top,REJECT
 - DOMAIN,13190546cd1dec9bbdc.com,REJECT
 - ……
 - IP-CIDR,223.252.192.0/19,DIRECT,no-resolve
 - GEOIP,CN,DIRECT
 - MATCH,𝐅𝐢𝐧𝐚𝐥
```

### 日志

```raw
[TCP] dial DIRECT (match DomainSuffix/360buyimg.com) 172.19.0.1:47428 --> m.360buyimg.com:43049 error: dial tcp 218.2xx.xx.xxx:43049: i/o timeout | dial tcp 218.2xx.xx.xxx:43049: i/o timeout | dial tcp 218.2xx.xx.xxx:43049: i/o timeout | dial tcp 218.2xx.xx.xxx:43049: i/o timeout | dial tcp 218.2xx.xx.xxx:43049: i/o timeout | dial tcp 218.2xx.xx.xxx:43049: i/o timeout | dial tcp 218.2xx.xx.xxx:43049: i/o timeout | dial tcp 218.2xx.xx.xxx:43049: i/o timeout | dial tcp 218.2xx.xx.xxx:43049: i/o timeout | dial tcp 218.2xx.xx.xxx:43049: i/o timeout
```
