### ISSUE TITLE
[BUG] "配置"中`自动更新`功能似乎失效，无法按指定的周期进行自动refresh

### ISSUE THREAD

**Issue by Kane-Kuroneko** [Kr328/ClashForAndroid#1942]
### 描述此错误

"配置"中`自动更新`功能似乎失效，无法按指定的周期进行自动refresh
clash app拥有后台常驻权限。

### 如何复现该错误

正常使用就有这个问题。

### 设备信息

两部手机均有这个问题：
- 机型: 魅族17PRO
- 系统类型: Flyme9
- Android 版本: 11

- 机型: IQOO10
- 系统类型:OriginOS3
- Android 版本:13

### 应用信息

- 版本: 2.5.12
- 安装包文件名: NULL
- 应用来源: Google Play Store

### 配置文件

```yml
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
proxies:
proxy-groups:
rules:
```

### 日志

```raw
日志均无异常
```

### 屏幕截图

![27bd8b89d73340cd07288b1307b4bf8](https://github.com/Kr328/ClashForAndroid/assets/40685018/1bf2af9b-9778-477f-882d-06bcf4b13450)
![1c88e3322de884b2bae25ba287d8603](https://github.com/Kr328/ClashForAndroid/assets/40685018/da725de9-a03d-437b-857b-dabd2402136e)
