### ISSUE TITLE
[BUG] 开启Clash 无法在谷歌商店下载Apk

### ISSUE THREAD

**Issue by fan-van** [Kr328/ClashForAndroid#1983]
### 描述此错误

打开Clash 开启全局模式，规则模式，自动代理，手动代理，都无法下载Apk。

### 如何复现该错误

步骤 1: ...
步骤 2: ...
步骤 3: ...
...

### 设备信息

- 机型: Vivo X90 pro
- 系统类型: OriginOS3
- Android 版本: 安卓13

### 应用信息

- 版本:2.5.12
- 安装包文件名: Clash for Android
- 应用来源:

### 配置文件

```yml
allow-lan: false
dns:
  ake-ip-range: 
  default-nameserver:
  - 
  - 
  enable: true
  nameserver:
  - 
  - 
  use-hosts: true
log-level: warning
mode: rule
proxies:
- alterId: 0
  cipher: auto
  name: 🇺🇸 Seattle V2 [8K]
  network: ws
  port: 80
  server: 41eed8f8-ryj6o0-s5v131-1xec.us-seav2.yxlmgs.com
  tls: false
  type: vmess
  uuid: 2cfef106-21ee-11ee-a25a-f23c93136cb3
  ws-headers:
    Host: 41eed8f8-ryj6o0-s5v131-1xec.us-seav2.yxlmgs.com
  ws-path: /
- alterId: 0
  cipher: auto
  name: 🇭🇰 Hongkong
  network: ws
  port: 80
  server: af02d116-ryj6o0-s5v131-1xec.ap-hk.189ti.com
  tls: false
  type: vmess
  uuid: 2cfef106-21ee-11ee-a25a-f23c93136cb3
  ws-headers:
    Host: af02d116-ryj6o0-s5v131-1xec.ap-hk.189ti.com
  ws-path: /
- alterId: 0
  cipher: auto
  name: 🇺🇸 San Francisco [4K]
  network: ws
  port: 3680
  server: 026e858e-ryj6o0-s5v131-1xec.fs.4nhui.com
  tls: false
  type: vmess
  uuid: 2cfef106-21ee-11ee-a25a-f23c93136cb3
  ws-headers:
    Host: 026e858e-ryj6o0-s5v131-1xec.fs.4nhui.com
  ws-path: /
- alterId: 0
  cipher: auto
  name: 🇺🇸 Seattle
  network: ws
  port: 80
  server: 00e811fd-ryj6o0-s5v131-1xec.us-seattle.yxlmgs.com
  tls: false
  type: vmess
  uuid: 2cfef106-21ee-11ee-a25a-f23c93136cb3
  ws-headers:
    Host: 00e811fd-ryj6o0-s5v131-1xec.us-seattle.yxlmgs.com
  ws-path: /
- alterId: 0
  cipher: auto
  name: 🇺🇸 Silicon Valley
  network: ws
  port: 80
  server: 22866168-ryj6o0-s5v131-1xec.us-svm.yxlmgs.com
  tls: false
  type: vmess
  uuid: 2cfef106-21ee-11ee-a25a-f23c93136cb3
  ws-headers:
    Host: broadcastlv.chat.bilibili.com
  ws-path: /
- alterId: 0
  cipher: auto
  name: 🇸🇬 Singapore
  network: ws
  port: 3681
  server: 5428bee7-ryj6o0-s5v131-1xec.fssg.4nhui.com
  tls: false
  type: vmess
  uuid: 2cfef106-21ee-11ee-a25a-f23c93136cb3
  ws-headers:
    Host: 5428bee7-ryj6o0-s5v131-1xec.fssg.4nhui.com
  ws-path: /
- alterId: 0
  cipher: auto
  name: 🇰🇷 Seoul
  network: ws
  port: 80
  server: c9d0f784-ryj6o0-s5v131-1xec.ap-seo.189ti.com
  tls: false
  type: vmess
  uuid: 2cfef106-21ee-11ee-a25a-f23c93136cb3
  ws-headers:
    Host: c9d0f784-ryj6o0-s5v131-1xec.ap-seo.189ti.com
  ws-path: /
- alterId: 0
  cipher: auto
  name: 🇯🇵 Tokyo
  network: ws
  port: 80
  server: 3b01c3ce-ryj6o0-s5v131-1xec.ap-tky.189ti.com
  tls: false
  type: vmess
  uuid: 2cfef106-21ee-11ee-a25a-f23c93136cb3
  ws-headers:
    Host: 3b01c3ce-ryj6o0-s5v131-1xec.ap-tky.189ti.com
  ws-path: /
- alterId: 0
  cipher: auto
  name: 🇬🇧 London
  network: ws
  port: 80
  server: 7b27426f-ryj6o0-s5v131-1xec.eu-lnd.yxlmgs.com
  tls: false
  type: vmess
  uuid: 2cfef106-21ee-11ee-a25a-f23c93136cb3
  ws-headers:
    Host: 7b27426f-ryj6o0-s5v131-1xec.eu-lnd.yxlmgs.com
  ws-path: /
proxy-groups:
- name: 🧭 用户选择
  proxies:
  - 🇺🇸 Seattle V2 [8K]
  - 🌐 自动选择
  - 🇭🇰 Hongkong
  - 🇺🇸 San Francisco [4K]
  - 🇺🇸 Seattle
  - 🇺🇸 Silicon Valley
  - 🇸🇬 Singapore
  - 🇰🇷 Seoul
  - 🇯🇵 Tokyo
  - 🇬🇧 London
  type: select
- interval: 1800
  name: 🌐 自动选择
  proxies:
  - 🇺🇸 Seattle V2 [8K]
  - 🇭🇰 Hongkong
  - 🇺🇸 San Francisco [4K]
  - 🇺🇸 Seattle
  - 🇺🇸 Silicon Valley
  - 🇸🇬 Singapore
  - 🇰🇷 Seoul
  - 🇯🇵 Tokyo
  - 🇬🇧 London
  type: url-test
  url: http://www.gstatic.com/generate_204
rules:
- DOMAIN-SUFFIX,cn.bing.com,DIRECT
- DOMAIN-SUFFIX,jego.vip,🧭 用户选择
- DOMAIN-SUFFIX,googletagservices.com,🧭 用户选择
- DOMAIN-SUFFIX,ggpht.com,🧭 用户选择
- DOMAIN-SUFFIX,gvt3.com,🧭 用户选择
- DOMAIN-SUFFIX,jego.pro,🧭 用户选择
- DOMAIN-SUFFIX,googlesyndication.com,🧭 用户选择
- DOMAIN-SUFFIX,googleapis.com,🧭 用户选择
- DOMAIN-SUFFIX,googlesource.com,🧭 用户选择
- DOMAIN-SUFFIX,googlegroups.com,🧭 用户选择
- DOMAIN-SUFFIX,google.com.tw,🧭 用户选择
- DOMAIN-SUFFIX,google.com.hk,🧭 用户选择
- DOMAIN-SUFFIX,gstatic.com,🧭 用户选择
- DOMAIN-SUFFIX,gmail.com,🧭 用户选择
- DOMAIN-SUFFIX,appspot.com,🧭 用户选择
- DOMAIN-SUFFIX,jegocloud.com,🧭 用户选择
- DOMAIN-SUFFIX,googleblog.com,🧭 用户选择
- DOMAIN-SUFFIX,jegocloud.net,🧭 用户选择
- DOMAIN-SUFFIX,wikimedia.org,🧭 用户选择
- DOMAIN-SUFFIX,android.com,🧭 用户选择
- DOMAIN-SUFFIX,chrome.com,🧭 用户选择
- DOMAIN-SUFFIX,wikipedia.org,🧭 用户选择
- DOMAIN-SUFFIX,google.com,🧭 用户选择
- DOMAIN-SUFFIX,googleusercontent.com,🧭 用户选择
- DOMAIN-SUFFIX,googleadservices.com,🧭 用户选择
- DOMAIN-SUFFIX,gvt2.com,🧭 用户选择
- DOMAIN-SUFFIX,google.co.jp,🧭 用户选择
- DOMAIN-SUFFIX,mediawiki.org,🧭 用户选择
- DOMAIN-SUFFIX,facebook.com,🧭 用户选择
- DOMAIN-SUFFIX,youtubeeducation.com,🧭 用户选择
- DOMAIN-SUFFIX,instagram.com,🧭 用户选择
- DOMAIN-SUFFIX,withyoutube.com,🧭 用户选择
- DOMAIN-SUFFIX,youtubekids.com,🧭 用户选择
- DOMAIN-SUFFIX,youtu.be,🧭 用户选择
- DOMAIN-SUFFIX,googlevideo.com,🧭 用户选择
- DOMAIN-SUFFIX,fbcdn.net,🧭 用户选择
- DOMAIN-SUFFIX,youtubei.googleapis.com,🧭 用户选择
- DOMAIN-SUFFIX,youtube.com,🧭 用户选择
- DOMAIN-SUFFIX,yt.be,🧭 用户选择
- DOMAIN-SUFFIX,youtubegaming.com,🧭 用户选择
- DOMAIN-SUFFIX,yt3.ggpht.com,🧭 用户选择
- DOMAIN-SUFFIX,youtube-nocookie.com,🧭 用户选择
- DOMAIN-SUFFIX,ytimg.com,🧭 用户选择
- DOMAIN-S
```

### 日志

```raw
Warning
10:22:36.406
[TCP] dialGLOBAL to
rr3---sn-2x3elnesxn--ngstr-cn-8za9o.com:443error:couldn'tfindip:rr3---sn-2x3elnes.xn--ngstr-cn-8za9o.com
10:22:3 6.383
Warning
[TCP] dialGLOBAL torr3---sn-2x3elnes.xn--ngstr-cn-8zao.com:443 error:couldn't findip:rr3---sn-2x3elnes.xn--ngstr-cn-8za9o.com
Warning
10:22:24.444
[TCP] dialGLOBAL torr2---sn-2x3elnel.xn--ngstr-cn-8za9o.com:443error:couldn'tfindip:rr2---sn-2x3elnel.xn--ngstr-cn-8za9o.com
Warning
10:22:24.432
[TCP] dialGLOBAL torr2---sn-2x3elnel.xn--ngstr-cn-8za9o.com:443error:couldn'tfindip:rr2---sn-2x3elnel.xn--ngstr-cn-8za9o.com
Warning
10:22:24.209
[TCP] dialGLOBAL torr|---sn-2x3elnel.xn--ngstr-cn-8za9o.com:443error:couldn't findip;rr|---sn-2x3elnel.xn--ngstr-cn-8za9o.com
```

### 屏幕截图

![日志图片](https://github.com/Kr328/ClashForAndroid/assets/42634166/626dd878-81f8-4302-b11f-729dbafd4b27)
