### ISSUE TITLE
[Feature Request] 支持clash relay类型代理组

### ISSUE THREAD

**Issue by KyonLi** [Kr328/ClashForAndroid#364]
**功能描述**
希望能够支持clash的relay类型代理组，以下配置在PC端工作正常，Android端报连接重置
```yaml
proxy-groups:
  - name: 🔄 代理转发
    type: relay
    proxies:
      - 1️⃣ 入口代理
      - 2️⃣ 出口代理

  - name: 1️⃣ 入口代理
    type: select
    proxies:
      - 🇭🇰 HK
      - 🇯🇵 JP
      - 🇺🇸 US

  - name: 2️⃣ 出口代理
    type: select
    proxies:
      - 🇭🇰 HK
      - 🇯🇵 JP
      - 🇺🇸 US
```

**描述你希望的实现方式**

**附加信息**
Dreamacro/clash/pull/539
