### ISSUE TITLE
[Feature Request] 在relay中支持DIRECT

### ISSUE THREAD

**Issue by Spedoske** [Kr328/ClashForAndroid#400]
**功能描述**

有以下配置文件
```
Proxy:
  - {name: "代理服务器"}
  - {name: "前置代理"}
Proxy Group:
  - name: 选择前置代理
    type: select
    proxies:
      - DIRECT
      - 前置代理
  - name: 使用代理
    type: relay
    proxies:
      - 选择前置代理
      - 代理服务器
```
当 选择前置代理 选择 Direct 时，无法连接代理服务器
，理想行为应该是忽略 Direct 项，直接连接代理服务器。

**描述你希望的实现方式**

relay 在 遇到 Direct 时更改处理逻辑。

**附加信息**
该功能在Android实现上不可用。在其他平台未经测试，可能要在 Dreamacro / clash上提交issue。

**错误信息**
```
dial xxx error : connect error: missing port in address.
```
