### ISSUE TITLE
[BUG] PC端可用的节点，在手机端没有一个可用，求解

### ISSUE THREAD

**Issue by Adam-Jin** [Kr328/ClashForAndroid#402]
**描述出现的错误**
请简洁的描述你遇到的错误
PC端可用的Clash配置，放到手机上一个节点都连不上。测速也不显示延迟.
看了日志。规则路由的没问题

**如何复现该错误**
复现步骤:
1. ...
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: 美版三星S9
 - 系统/ROM: 
 - Android 版本 [例如: 8]
 - ROM版本 

**应用信息**
 - 版本: [例如: 1.2.15]
 - 安装包文件名: [例如: app-release-arm64-v8a.apk]
 - 应用来源: github

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
port: 7890
socks-port: 7891
redir-port: 0
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
secret: ""
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 117.50.10.10
    - 119.29.29.29
    - 114.114.114.114
    - 223.5.5.5
    - 223.6.6.6
  fallback:
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://dns.google:853
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```
