### ISSUE TITLE
[BUG] 没有监听DNS端口。关闭”DNS配置覆盖“后没有使用配置文件中的DNS。

### ISSUE THREAD

**Issue by Quackgrass** [Kr328/ClashForAndroid#453]
**描述出现的错误**
1. 没有监听DNS端口。日志中显示 `DNS server listening at: :0` 
2. 关闭”DNS配置覆盖“后没有使用配置文件中的DNS。

**如何复现该错误**
复现步骤:
1. 每次启动后，日志都是如此。

**预期行为**
日志中应该正确显示监听的端口。如HTTP和SOCKS一样。
adguard 可以添加 127.0.0.1:5354 为DNS，而不是提示无连接。

**屏幕截图**
![photo_2020-06-24_18-58-12](https://user-images.githubusercontent.com/42032091/85543472-afb70b80-b64c-11ea-80ac-1f4cbb87cfc4.jpg)

**设备信息 (请完成以下信息):**
 - 机型: 小米Note3
 - 系统/ROM: MIUI12
 - Android 版本: 9
 - ROM版本: 20.6.18

**应用信息**
 - 版本: 2.0.3
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源:  GitHub release

**附加信息**
其他的可能与改错误相关的信息

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
dns:
  enabled: true
  ipv6: false
  listen: 127.0.0.1:5354
  default-nameserver:
    - 119.29.29.29
    - 1.0.0.1
  enhanced-mode: redir-host
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
  fallback:
    - tls://1.0.0.1
    - tls://dns.google
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
[2020-06-24 190318.log.txt](https://github.com/Kr328/ClashForAndroid/files/4824943/2020-06-24.190318.log.txt)
```
