### ISSUE TITLE
[BUG] Empty Profile错误

### ISSUE THREAD

**Issue by YamazakuraH** [Kr328/ClashForAndroid#470]
**描述出现的错误**
配置文件是有内容的，上一个版本还能用。

**如何复现该错误**
复现步骤:
1. 因为机场配置文件还是旧版所以我用了subconverter来切换到新版
2. 转换后再clash中无法识别

**预期行为**
正确识别

**屏幕截图**
![Screenshot_2020-06-30-12-35-25-537_com.github.kr328.clash.jpg](https://user-images.githubusercontent.com/62797066/86084445-83c5db00-bacf-11ea-9116-bc07a49ea310.jpg)

**设备信息 (请完成以下信息):**
 - 机型: Xiaomi 9
 - 系统/ROM: MIUI11
 - Android 版本 10
 - ROM版本 20.6.18

**应用信息**
 - 版本: 2.0.8
 - 安装包文件名: app-arm64-v8a-release
 - 应用来源: GitHub

**附加信息**

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
Proxy: ~
Proxy Group: ~
Rule: ~
proxies:
proxy-groups:
  - name: 🔰 节点选择
    type: select
    proxies:
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 0
    proxies:
  - name: 🌍 国外媒体
    type: select
    proxies:
  - name: 🌏 国内媒体
    type: select
    proxies:
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
  - name: 📲 电报信息
    type: select
    proxies:
  - name: 🍎 苹果服务
    type: select
    proxies:
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
rules:
```

**日志**
```
12:40:48 |INFO| [TCP] <nil>: --> arukasapi.herokuapp.com match Match using Final[BGP高级>>日本B]
```
