### ISSUE TITLE
[BUG] 在谷歌pixel 3上无法正常工作

### ISSUE THREAD

**Issue by danywheeler** [Kr328/ClashForAndroid#486]
**描述出现的错误**
无法正常工作，看上去一直没连接上代理服务器。

**如何复现该错误**
开启代理

**预期行为**
能正常工作

**屏幕截图**
![image](https://user-images.githubusercontent.com/8910772/86447962-ad3d6b80-bd48-11ea-85b9-650f626e4c7a.png)

**设备信息 (请完成以下信息):**
 - 机型:  Pixel 3
 - 系统/ROM:  original
 - Android 版本 : 10
 - ROM版本: 不适用

**应用信息**
 - 版本: v2.0.11
 - 安装包文件名:  不适用
 - 应用来源: Google Play

**附加信息**
同样的订阅配置在v2rayNG中工作正常

**配置文件**
```yaml
port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: ''
proxies:
...
proxy-groups:
...
rules:
...
```

**日志**
```
已截图
```
