### ISSUE TITLE
[BUG] 可以请问一下k大软件内置的dns替换的具体内容吗？

### ISSUE THREAD

**Issue by finemist** [Kr328/ClashForAndroid#489]
**描述出现的错误**
请简洁的描述你遇到的错误

由于我想设置一个ipv6地址的dns，所以我关闭了dns配置覆盖，配置如下，这时当我访问诸如ip.sb这种网站，却只能检测出ipv4地址，这时我的nat类型为full cone，可以使用google voice进行通话。当我将增强模式改为fake-ip时，ip.sb可以检测出ipv4和ipv6地址，但是此时nat类型检测为symmetric cone，无法正常使用google voice通话。可是我使用软件内置dns则可以正常检测出双栈地址，同时nat类型为full cone。我只能通过log得知内置dns所设置的几个dns地址，但是没法获知整个细节，恳请开发者大大告知软件内置的dns配置。

**如何复现该错误**
复现步骤:
1. 关闭dns配置覆盖即可
2. ...
3. ...
4. ...

**预期行为**
清晰简单的描述你预期的应用应该表现的行为
可以在关闭dns配置覆盖后实现相同的效果
**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: [例如: Pixel 4]
 - 系统/ROM: [例如: MIUI 11]
 - Android 版本 [例如: 10]
 - ROM版本 [例如: 20.3.19]

**应用信息**
 - 版本: [2.0.11]
 - 安装包文件名: [app-release-arm64-v8a.apk]
 - 应用来源: [Google Play]

**附加信息**
其他的可能与改错误相关的信息
软件没有bug，是我不会配置
**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
port: 7890
socks-port: 7891
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: '0.0.0.0:9090'
interface-name: en0
experimental:
  ignore-resolve-fail: true
dns:
  enable: true
  ipv6: true
  listen: '0.0.0.0:53'
  default-nameserver:
    - 119.29.29.29      
    - 8.8.8.8      
  enhanced-mode: redir-host    
  nameserver:
    - 119.29.29.29
    - '[2400:3200::1]:53'
  fallback:
    - 'tls://dns.google:853'
    - 'https://doh.rixcloud.dev/dns-query'
    - 'tls://dns.rubyfish.cn:853'
    - 'https://dns.cloudflare.com/dns-query'
  fallback-filter:
    geoip: true 
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```
