### ISSUE TITLE
[BUG] PC端能正常链接的HTTP Clash无法链接

### ISSUE THREAD

**Issue by sirstrone** [Kr328/ClashForAndroid#501]
**描述出现的错误**
请简洁的描述你遇到的错误
dial GLOBAL error: read tcp4 10.9.22.3:38584->47.241.60.112:8590: read: connection reset by peer
**如何复现该错误**
复现步骤:
在任何模式 链接此Http代理时 均提示上述错误
PC端可以正常链接
服务器对应端口已打开

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
# 在此粘贴
# HTTP 代理端口
port: 42177

# SOCKS5 
#socks-port: 7891

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
# redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: false

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Global

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# clash 的 RESTful API
external-controller: 127.0.0.1:9090

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `${API}/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder

# RESTful API 的口令 (可选)
# secret: ""

# 代理节点
Proxy:
# 更多协议配置示例：https://github.com/Dreamacro/clash/blob/master/README.md


# 加密算法推荐：AEAD_AES_128_GCM AEAD_AES_192_GCM AEAD_AES_256_GCM AEAD_CHACHA20_POLY1305

- { name: "UnblockNeteaseMusic", type: http, server: 47.241.60.112 , port: 8590}

Rule: 
# LAN
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,17.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- `MATCH,UnblockNeteaseMusic
```
服务器没什么用 就不码了

求大佬们帮我测试一下问题出现在哪
