### ISSUE TITLE
[BUG] 更新至 2.0.15 后代理无法正常启动

### ISSUE THREAD

**Issue by yangon99** [Kr328/ClashForAndroid#514]
**描述出现的错误**
自 2.0.10 更新至 2.0.15 后，点击启动后会回报错误 “too many open files”，或 “cursor window allocation of …… bytes failed”。

**如何复现该错误**
在主界面点击启动按钮后，稍后会在下方浮现错误提示。
回退安装 2.0.10-2.0.14 版本均可正常使用

**预期行为**
正常启动代理

**屏幕截图**
[too many open files 错误截图](https://user-images.githubusercontent.com/54441244/87271951-5c2b3580-c507-11ea-8189-51b013d1843f.png)
[allocate faild 错误截图](https://user-images.githubusercontent.com/54441244/87272021-9c8ab380-c507-11ea-85f7-d4ddca85fced.png)

**设备信息 (请完成以下信息):**
 - 机型: Honor 6X
 - 系统/ROM: LineageOS
 - Android 版本: 9
 - ROM版本: 16.0

**应用信息**
 - 版本: 2.0.15
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: github release

**附加信息**
暂无

**配置文件**
配置文件部分内容如下：
```yaml
proxy-providers:
  UnblockNetease:
    health-check:
      enable: false
      interval: 12000
      url: http://www.gstatic.com/generate_204
    interval: 86400
    path: ./unblock.yaml
    type: http
    url: https://example.com/unblock.yaml
  Mine:
    health-check:
      enable: false
      interval: 12000
      url: http://www.gstatic.com/generate_204
    interval: 86400
    path: ./mine.yaml
    type: http
    url: https://example.com/mine.yaml
proxy-groups:
  - name: PROXY
    type: select
    use:
      - Mine
  - name: NeteaseMusic
    type: select
    use:
      - UnblockNetease
  - name: Domestic
    proxies:
      - DIRECT
    type: select

rules:
  # 过长省略
allow-lan: true

external-controller: 127.0.0.1:9090
log-level: debug
mode: Rule
port: 7890
socks-port: 7891
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    # DNS From USTC
    - 223.5.5.5
    - 119.28.28.28
    - 1.2.4.8
  fallback:
    - tls://dns.adguard.com:853
    - tls://1.1.1.1:853
    - tls://dns.google:853
```

**日志**
[too many open files 日志（logcat）](https://gist.github.com/yangon99/0bea62ae595f0e858d3331aa269938af)
[aloocate failed 日志（logcat）](https://gist.github.com/yangon99/c3d38a3afd2e9adc7b1c8a20970f484b)
