### ISSUE TITLE
[BUG] 系统 DNS 没有正常工作

### ISSUE THREAD

**Issue by CzBiX** [Kr328/ClashForAndroid#515]
**描述出现的错误**
我在路由器上的 DNS 手动配置了 A 记录，并在 rules 里添加了域名的 `DOMAIN-SUFFIX` 直连规则。
在手机上开启 Clash 就无法正常访问这个域名，关闭 Clash 就没有问题。
电脑端 Clash 没有问题。

**如何复现该错误**
复现步骤:
1. 手机默认使用路由器的 DNS
2. 启动 Clash，并开启 Append System DNS。（DNS Config Override 开关不影响结果。）
3. 在浏览器中访问域名失败。

**预期行为**
正确解析出指定的 IP 并正常访问。

**应用信息**
 - 版本: 2.0.15
 - 应用来源: Google Play

**附加信息**
通过查看日志可以看出路由器 IP 作为 System DNS 有正常添加到配置中，但并没有该域名的解析记录（？）
然后看到是访问了公网 DNS 解析出来的 IP，而非我在路由器指定的 IP。

**配置文件**
没有配置 DNS 相关选项。

**Comment by Kr328** [comment]
内置的 DNS 配置 在 返回 内网地址 和 0.0.0.0/32 127.0.0.0/8 时 会使用 fallback

关掉 DNS 覆盖 自行编写 DNS 配置即可

**Comment by CzBiX** [comment]
感谢，添加下面的配置后正常了。

```yaml
dns:
  enable: true
  nameserver:
    - 223.5.5.5
    - 1.1.1.1
  fallback-filter:
    geoip: true
```

不过我好奇为什么 `fallback-filter.geoip` 默认不开呢？
毕竟 Clash 的默认配置是开的来着。
