### ISSUE TITLE
[BUG] 使用自定义DNS出现Start DNS server error: listen udp 0.0.0.0:53: bind: permission denied

### ISSUE THREAD

**Issue by ccboxes** [Kr328/ClashForAndroid#530]
**描述出现的错误**
如题，使用自定义DNS日志中出现
Start DNS server error: listen udp 0.0.0.0:53: bind: permission denied

**如何复现该错误**
复现步骤:
1. 在DNS配置中绑定0.0.0.0:53
2. 启用配置

**预期行为**
成功绑定端口并接受vpn service劫持的DNS请求

**屏幕截图**
如果适用, 上传屏幕截图以帮助描述错误

**设备信息 (请完成以下信息):**
 - 机型: honor v30 pro
 - 系统/ROM: EMUI 10.1
 - Android 版本 10

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 8.8.8.8
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - "*.*.*.*.srv.nintendo.net"
    - "*.*.*.stun.playstation.net"
    - xbox.*.microsoft.com
    - "*.*.*.xboxlive.com"
  nameserver:
    - tls://h9b8i2.dbj.rubyfish.cn:853
    - tls://223.5.5.5:853
  fallback:
    - tls://1.1.1.1:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
Start DNS server error: listen udp 0.0.0.0:53: bind: permission denied
```
