### ISSUE TITLE
[BUG] v2.0.18 不支持自定义 Hosts

### ISSUE THREAD

**Issue by dbarobin** [Kr328/ClashForAndroid#553]
**描述出现的错误**
v2.0.18 不支持自定义 Hosts，回退版本到 v2.0.16 可以正常使用。

**如何复现该错误**
复现步骤:
1. 安装 v2.0.18；
2. 通过 URL 订阅；
3. 启动 Clash；
4. Chrome 浏览器访问自定义 Hosts；
5. Hosts 无法打开。

**预期行为**
应用正常，但是自定义 Hosts 无法打开。

**屏幕截图**
无。

**设备信息 (请完成以下信息):**
 - 机型: OnePlus
 - 系统/ROM: H2OS
 - Android 版本：10
 - ROM版本：10.0.4

**应用信息**
 - 版本: 2.0.18
 - 安装包文件名:  app-universal-release.apk
 - 应用来源: APK 直接安装

**附加信息**
无。

**配置文件**

```yaml
hosts:
  'xxx.xxx.com': xxx.xxx.xxx.xxx

rules:
  - DOMAIN-KEYWORD,*.xxx.com,DIRECT
  - DOMAIN-SUFFIX,xxx.xxx.com,DIRECT
```

**日志**
无。
