### ISSUE TITLE
[BUG] 无法正常进行持续代理

### ISSUE THREAD

**Issue by Sanczzg** [Kr328/ClashForAndroid#579]
**描述出现的错误**
Clash配置无问题(在Clash for Windows 以及 ClashX Pro均可正常使用)。启动代理后平均大约五秒后，手机状态栏处的VPN钥匙图标会消失，检查后发现Clash代理关闭，可无限复现。开启“自动重启”无效。日志功能在代理异常前可正常输出日志，出现异常后日志（包含之前已有日志）全部为空。

**预期行为**
正常维持代理。

**设备信息 (请完成以下信息):**
 - 机型: Oneplus 7 Pro
 - 系统/ROM: Oxygen OS
 - Android 版本: 10
 - ROM版本: 10.3.3.GM21AA

**应用信息**
 - 版本: 2.0.18
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: Github Release

**附加信息**
测试回退版本，发现**2.0.17**可正常运行。可以对2.0.18的所有更新部分进行排查。
并非只有这一部设备出现问题。经过多个朋友不同安卓机的反馈（同配置文件），在此版本出现的问题类似。

**配置文件**
附上配置文件
```yaml
mixed-port: 7890
allow-lan: true
ipv6: false
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    ipv6: false
    default-nameserver: [119.29.29.29, 156.154.70.5]
    enhanced-mode: redir-host
    nameserver: ['tls://rubyfish.cn', 'tls://dns.rubyfish.cn', 'tls://dns.alidns.com']
    fallback: ['tls://cloudflare-dns.com', 'tls://dns.google', 'tls://435d75.dns.nextdns.io']
    fallback-filter: { geoip: true }
proxies:

proxy-groups:
    - { name: 示例, type: select, proxies: [韩国01, 香港01, 美国01] }
    - { name: StreamingSE, type: select, proxies: [DIRECT, 韩国01, 香港01, 美国01] }
    - { name: Zoom, type: select, proxies: [DIRECT, 韩国01, 香港01, 美国01] }
    - { name: Final, type: select, proxies: [抑郁云, DIRECT, 韩国01, 香港01, 美国01] }
rule-providers:
    Unbreak: { type: http, behavior: classical, path: ./Rules/DivineEngine/Profiles/RuleSet/Unbreak.yaml, url: '示例', interval: 86400 }
    Streaming: { type: http, behavior: classical, path: ./Rules/DivineEngine/Profiles/RuleSet/StreamingMedia/Streaming.yaml, url: '示例', interval: 86400 }
    StreamingSE: { type: http, behavior: classical, path: ./Rules/DivineEngine/Profiles/RuleSet/StreamingMedia/StreamingSE.yaml, url: '示例', interval: 86400 }
    Global: { type: http, behavior: classical, path: ./Rules/DivineEngine/Profiles/RuleSet/Global.yaml, url: '示例', interval: 86400 }
    OneDrive: { type: http, behavior: classical, path: ./Rules/DivineEngine/Profiles/RuleSet/Extra/Microsoft/OneDrive.yaml, url: '示例', interval: 86400 }
    Zoom: { type: http, behavior: classical, path: ./Rules/Sanczzg/FrustratingJoyMaintain/Rules/Zoom.yaml, url: '示例', interval: 86400 }
    China: { type: http, behavior: classical, path: ./Rules/DivineEngine/Profiles/RuleSet/China.yaml, url: '示例', interval: 86400 }
    ChinaIP: { type: http, behavior: ipcidr, path: ./Rules/DivineEngine/Profiles/RuleSet/Extra/ChinaIP.yaml, url: '示例', interval: 86400 }
rules:
    - 'RULE-SET,Unbreak,DIRECT'
    - 'RULE-SET,Streaming,示例'
    - 'RULE-SET,StreamingSE,StreamingSE'
    - 'RULE-SET,Zoom,Zoom,no-resolve'
    - 'RULE-SET,OneDrive,示例'
    - 'RULE-SET,Global,示例'
    - 'RULE-SET,China,DIRECT'
    - 'IP-CIDR,192.168.0.0/16,DIRECT'
    - 'IP-CIDR,10.0.0.0/8,DIRECT'
    - 'IP-CIDR,172.16.0.0/12,DIRECT'
    - 'IP-CIDR,127.0.0.0/8,DIRECT'
    - 'IP-CIDR,100.64.0.0/10,DIRECT'
    - 'IP-CIDR,224.0.0.0/4,DIRECT'
    - 'RULE-SET,ChinaIP,DIRECT'
    - 'MATCH,Final'

```
