### ISSUE TITLE
[Feature Request] 节点名称简化显示功能希望回归

### ISSUE THREAD

**Issue by Xlyaon** [Kr328/ClashForAndroid#593]
**功能描述**
回归节点名称显示简化的功能，这样显示更加整洁

**描述你希望的实现方式**
与2.0.18以及之前版本相同的简化节点名称

**附加信息**
无

**Comment by AkariiinMKII** [comment]
```
现已增加的 Clash for Android 特有的 配置字段

clash-for-android:
  append-system-dns: true # 追加系统 DNS 到 nameserver
  ui-subtitle-pattern: # 用于处理代理统一前缀的正则表达式 命中该正则表达式的 *代理组名称片段* 将会改为在 *代理信息的子标题* 显示
```
