### ISSUE TITLE
[BUG]  汇入配置失败 Initial rule provider Streaming error: not support on this platfrom

### ISSUE THREAD

**Issue by phlinhng** [Kr328/ClashForAndroid#611]
在 v2board 面板的机场上按一键匯入，出现提示 Initial rule provider Streaming error: not support on this platform

**如何复现该错误**
复现步骤:
1. 新增配置
2. CFA 开始下载配置
3. 出现下载失败

**预期行为**
正常匯入配置并使用

**设备信息 (请完成以下信息):**
 - 机型: Samsung A51 5G
 - 系统/ROM: OneUI 2.1
 - Android 版本: 10
 - ROM版本: OneUI 2.1

**应用信息**
 - 版本: 2.0.17
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: Github

**附加信息**

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
rule-providers:
    Streaming: { type: http, behavior: classical, path: ./RuleSet/StreamingMedia/Streaming.yaml, url: 'https://raw.fastgit.org/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml', interval: 86400 }
    PayPal: { type: http, behavior: classical, path: ./RuleSet/Extra/Paypal.yaml, url: https://raw.fastgit.org/DivineEngine/Profiles/master/Clash/RuleSet/Extra/PayPal.yaml', interval: 86400 }
    Global: { type: http, behavior: classical, path: ./RuleSet/Global.yaml, url: 'https://raw.fastgit.org/DivineEngine/Profiles/master/RuleSet/Global.yaml', interval: 86400 }
    China: { type: http, behavior: classical, path: ./RuleSet/China.yaml, url: https://raw.fastgit.org/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml', interval: 86400 }
    ChinaIP: { type: http, behavior: ipcidr, path: ./RuleSet/Extra/ChinaIP.yaml, url: 'https://raw.fastgit.org/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml', interval: 86400 }
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
<在此粘贴>
```
