### ISSUE TITLE
[BUG] hosts 不起作用

### ISSUE THREAD

**Issue by limon** [Kr328/ClashForAndroid#643]
**描述出现的错误**
自定义hosts无效；同样配置文件在软路由的 clash 上有效

**如何复现该错误**
复现步骤:
1. 设置了 hosts: 'nas': 192.168.1.100 等解析；具体见下面配置文件
2. 覆写dns设置为：首选配置文件
3. 浏览器输入nas无法解析

**设备信息 (请完成以下信息):**
 - 机型: Mix2S
 - 系统/ROM: MIUI 12.0.1
 - Android 版本 10

**应用信息**
 - 版本: 2.1.5
 - 安装包文件名: app-arm64-v8a-release.apk
 - 应用来源: github

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
port: 7890 # Http代理端口
socks-port: 7891 # Socks 代理端口
redir-port: 7892 # 转发端口
allow-lan: true
mode: Rule
ipv6: false
log-level: silent
hosts:
  'nas': 192.168.1.100
  'i.ytimg.com': 172.217.175.22
  'ci.phncdn.com': 152.195.33.132
dns:
  enable: true
  use-hosts: true
  listen: 0.0.0.0:53 # 5300 也试过
  enhanced-mode: redir-host
  nameserver:
    - 114.114.114.114
  fallback:
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true # 默认
    ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
      - 240.0.0.0/4
```
