### ISSUE TITLE
[BUG] network issues on some routers

### ISSUE THREAD

**Issue by fsheidaiee** [Kr328/ClashForAndroid#737]
**Describe the bug**
Hello when I tap start in clash. on some routers as an example ZyXEL DEL1201, the whole internet get disconnected. not only for me but also for everyone who is using internet on that router, and after I disconnect clash, everyone can use the internet again without problem. the problem does not occur in clash-in-windows program on the same router, while I'm using a mutual profile in both windows and android.
 I have noticed that on some routers I don't have this issue at all.

**Expected behavior**
fix this issue

**Device Info (please complete the following information):**

 - Device: [Samsung A70]
 - ROM: [stock rom]
 - ROM Version: one UI 2.0
 - Android Version [10]

**Application Info (please complete the following information):**

 - Version: [tried both 2.1.5 from play store and 2.1.6 from github]
 - Apk File Name: [app-release-arm64-v8a.apk]
 - Distribution Channel: [Google Play & [github](https://github.com/Kr328/ClashForAndroid/releases/download/v2.1.6/app-arm64-v8a-release.apk)]

**Configure**
If applicable, paste **removed server info** configure
```yaml
port: 7890
socks-port: 7891
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
dns:
  enable: false
  listen: 0.0.0.0:53
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 114.114.114.114
    - 8.8.8.8
    - tls://dns.rubyfish.cn:853
    - https://1.1.1.1/dns-query

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 864000

rules:
  - IP-CIDR,192.168.0.0/16,🎯 Dirconnection,no-resolve
  - IP-CIDR,10.0.0.0/8,🎯 Dirconnection,no-resolve
  - IP-CIDR,172.16.0.0/12,🎯 Dirconnection,no-resolve
  - IP-CIDR,127.0.0.0/8,🎯 Dirconnection,no-resolve
  - IP-CIDR,100.64.0.0/10,🎯 Dirconnection,no-resolve
  - IP-CIDR6,::1/128,🎯 Dirconnection,no-resolve
  - IP-CIDR6,fc00::/7,🎯 Dirconnection,no-resolve
  - IP-CIDR6,fe80::/10,🎯 Dirconnection,no-resolve
  - IP-CIDR6,fd00::/8,🎯 Dirconnection,no-resolve
  - RULE-SET,reject,🛑 Stop
  - DOMAIN-SUFFIX,ad.com,🛑 Stop
  - SRC-IP-CIDR,192.168.1.201/32,🎯 Dirconnection
  - GEOIP,IR,🎯 Dirconnection
  - MATCH,,Best

**Logs**
all the logs say that cannot connect to server

```
