### ISSUE TITLE
安卓手机纯ipv6网站（bt.byr.cn）无法代理[BUG] 

### ISSUE THREAD

**Issue by NEOherozzz** [Kr328/ClashForAndroid#750]
**描述出现的错误**
安卓手机纯ipv6网站（bt.byr.cn）无法代理，显示找不到bt.byr.cn的服务器ip地址 DNS_PROBE_FINISHED_NXDOMAIN。
WIFI网络只有ipv4，但是远端服务器是ipv4+ipv6，能够连接到bt.byr.cn。同样的配置在电脑clashWeb上能够打开bt.byr.cn。

**如何复现该错误**
复现步骤:
1. 下载yaml文件
2. 打开clash for android
3. 代开chrome，输入bt.byr.cn
4. 无法访问

**预期行为**
能够代理纯ipv6网站

**屏幕截图**
无

**设备信息 (请完成以下信息):**
 - 机型: [HUAWEI P20pro CLT-AL00]
 - 系统/ROM: [EMUI 10.0.0.180]
 - Android 版本 [10]
 - ROM版本 [官方]

**应用信息**
 - 版本: [2.1.6]
 - 安装包文件名: [app-arm64-v8a-release.apk]
 - 应用来源: [Github]

**附加信息**
日志级别为debug，但是打开网站没有显示相关记录。
尝试过配置：
        ipv6（false）+dns（false）--》电脑可以，手机不行
        ipv6（true）+dns（false）--》电脑可以，手机不行
        ipv6（false）+dns（true）--》电脑可以，手机不行
        ipv6（true）+dns（true）--》电脑可以，手机不行
私认为ipv6数据包没有到vpnservice？
我看别人博客之前版本：设置-》网络-》vpnservice选项里面有ipv6开关，现在为啥没有了？

**配置文件**
如果适用, 在此粘贴 **去除服务器信息的** 的 **配置文件**
```yaml
mixed-port: 7890
allow-lan: false
bind-address: '*'
mode: rule
log-level: debug
ipv6: true
external-controller: 127.0.0.1:9090
hosts:
  'mtalk.google.com': 108.177.125.188
  't.cn': 203.107.55.116
     
dns:
    enable: true   # 打开 DNS 接管
    listen: 0.0.0.0:53
    default-nameserver:
        - 223.5.5.5
        - 1.0.0.1
    enhanced-mode: redir-host
    fake-ip-range: 198.18.0.1/16
    nameserver:
        - 223.5.5.5
        - 1.0.0.1
        - https://1.0.0.1/dns-query
        - https://dns.google/dns-query
    fallback:
        - https://1.0.0.1/dns-query
        - https://dns.google/dns-query
    fallback-filter:
    geoip: true
    ipcidr:
        - 240.0.0.0/4     
 
proxies:
  - name: LosAngles
    server: 
    port: 443
    type: vmess
    uuid: 
    alterId: 64
    cipher: auto
    tls: true
    network: ws
    ws-path: 
    ws-headers:
      Host: 

proxy-groups:
  - name: 🚀 vps加速
    type: select
    proxies:
      - 🚀 节点选择
      - DIRECT
   ... ...

rules:
  - DOMAIN-SUFFIX,byr.cn,🚀 vps加速
  ... ...
```

**日志**
如果适用, 粘贴日志以帮助侦测错误
```
收集不到日志
```
