### ISSUE TITLE
[BUG] REJECT规则响应过慢

### ISSUE THREAD

**Issue by happy-tao** [Kr328/ClashForAndroid#905]
**描述出现的错误**
chrome打开网页对于广告屏蔽的Reject规则响应过慢。

**如何复现该错误**
复现步骤:
1. 添加屏蔽广告规则
    `-DOMAIN-SUFFIX,kanwby.com,REJECT`
    `-DOMAIN-SUFFIX,wtztkpy.cn,REJECT`
    `-DOMAIN-SUFFIX,bigcooe.xyz,REJECT`
    `-DOMAIN-SUFFIX,cnzz.com,REJECT` 
2. 以规则模式打开clash
3. 使用chrome打开[链接](https://m.xsw55.net/0/829/36343318.html)
4. 页面一直在等待响应完毕，期间时间很长

**预期行为**
迅速拒绝Reject的请求

**屏幕截图**
![Snipaste_2021-04-13_15-42-00.png](https://i.loli.net/2021/04/13/hc4sEVKZBnWQfT9.png)

**设备信息 (请完成以下信息):**
 - 机型: Redmi K30 Ultra
 - 系统/ROM: MIUI 12.5 
 - Android 版本: 11
 - ROM版本: 21.4.7
 - Chrome版本: 89.0.4389.105

**应用信息**
 - 版本: 2.3.12
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: GitHub

**附加信息**
2.3.11也存在类似的问题，2.1.6表现正常

**配置文件**
```yaml
proxy-groups:
  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
rules:
  -DOMAIN-SUFFIX,kanwby.com,🛑 全球拦截
  -DOMAIN-SUFFIX,wtztkpy.cn,🛑 全球拦截
  -DOMAIN-SUFFIX,bigcooe.xyz,🛑 全球拦截
  -DOMAIN-SUFFIX,cnzz.com,🛑 全球拦截
```
